### ISSUE TITLE
Deepin file manager selects other files as well

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#1]
If we try to select some files using dde-file-manager, then it selects some other files as well. Here's a picture of it.
![deepin-screen-recorder_dde-file-manager_20180309141334](https://user-images.githubusercontent.com/33563064/37197324-967b64fa-23a4-11e8-95cb-aed2eb7c3754.gif)

**Comment by ghost** [comment]
This is a default feature to let you select multiple line files more easily. If you want to select exact two files, select one ,and press "ctrl" and select others.

**Comment by SiamSami** [comment]
Oh... Thank you for telling me about it!

**Comment by gomes2191** [comment]
Standard Operating System Feature.

**Comment by zccrs** [comment]
Hi,
Thank you for your fallback.
That is a feature.
