### ISSUE TITLE
Cannot disable directory MIME type association / 无法取消目录文件关联

### ISSUE THREAD

**Issue by tribbloid** [linuxdeepin/dde-file-manager#10]
If a typical linux user has multiple alternative file manager(s) installed (e.g. Nautilus, Nemo, Dolphin, Thunar) and would like to replace DDE file manager with one of them for daily use. She will usually do one of the following:

- right click on a directory in Nautilus/Nemo and change file association to the target file manager.

- edit both ~/.config/mimeapps.list and /usr/share/applications/mimeapps.list and change all application path associated with MIME type inode/directory to the target file manager

NONE of these works: after every reboot / login DDE will revert ~/.config/mimeapps.list to it's own file manager. This caused a major UX collapse as some Linux applications rely on the latest Nautilus/Nemo commandline arguments that are not yet supported by DDE file manager.

Please introduce an option to disable file association check like Google Chrome and FireFox.

Tested on DDE 15.5 / file manager 1.6.2

**Comment by tribbloid** [comment]
related to https://github.com/linuxdeepin/dde-file-manager/commit/1e5a742304c6f2ab5cc66a9c537e0702a0c32caa#diff-7beb846669e41ae67ecfb37e81bc6071.

Any bypass on this?

**Comment by sbwtw** [comment]
@manateelazycat

**Comment by tribbloid** [comment]
what's the test release channel? last release was long time ago

**Comment by BLumia** [comment]
> @tribbloid : what's the test release channel? last release was long time ago

Current development branch is **master** branch.

> Any bypass on this?

Simply comment [line 182 at main.cpp](https://github.com/linuxdeepin/dde-file-manager/blob/4.7.1.2/dde-file-manager/main.cpp#L182) and rebuild the file manager will solve your problem.

> Please introduce an option to disable file association check like Google Chrome and FireFox.

Will probably provide a configurable option later, keep an eye on it :)

**Comment by zccrs** [comment]
@wangjia12 The DDE File Manager can is set default application for the "inode/directory" now, so, We can no longer disable change the  directory MIME type association？

**Comment by wangjia12** [comment]
> @wangjia12 The DDE File Manager can is set default application for the "inode/directory" now, so, We can no longer disable change the directory MIME type association？

那个功能就附带的取消这个限制吧

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40074/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
