### ISSUE TITLE
Tag folder is not removed immediately

### ISSUE THREAD

**Issue by gomes2191** [linuxdeepin/dde-file-manager#11]
Tag folder is not removed immediately upon removal in the file manager, it is necessary to restart the file manager to complete the removed of the folder tag.
Below is the GIF with the demonstration of the reported problem.

![bug](https://user-images.githubusercontent.com/4576117/40261867-92948602-5ad9-11e8-8ac7-2806aa27fd0d.gif)

As it was seen in the gif after the removal is not immediately removed the tag being necessary to restart the file manager for the removal to be completed.

File manager version 1.7

**Comment by SHIHUAMarryMe** [comment]
Hi, this problem had fixed. Please wait for updating next.

**Comment by BLumia** [comment]
Hi, please update your dde-file-manager and take a look if we already solved this issue. If you got any problem, feel free to reopen this issue :smile:
