### ISSUE TITLE
加了颜色标记的文件，再右键-标记信息，文件管理器就会退出

### ISSUE THREAD

**Issue by zoze0** [linuxdeepin/dde-file-manager#12]
更新1.7后，在加了颜色标记的文件上再右键-标记信息就会退出， 我在终端看了下信息是：
`2018-05-19, 14:23:27.270 [Debug  ] [dfilemenumanager.cpp DFileMenuManager::actionTriggered   1010] QAction(0x559de83f3280 text="标记信息" toolTip="标记信息" menuRole=TextHeuristicRole visible=true) QAction(0x559de83f3280 text="标记信息" toolTip="标记信息" menuRole=TextHeuristicRole visible=true)
2018-05-19, 14:23:27.270 [Debug  ] [dfilemenumanager.cpp DFileMenuManager::actionTriggered   1012] "标记信息" "标记信息"
fish: 'dde-file-manager' terminated by signal SIGSEGV (Address boundary error)`

**Comment by gomes2191** [comment]
Would this bug be reported in removing the correct bookmark? if so it has already been reported in #11

**Comment by SHIHUAMarryMe** [comment]
@licardoY 有没有gif之类的......单单log我也看不出来问题....

**Comment by zoze0** [comment]
在论坛发了贴 https://bbs.deepin.org/forum.php?mod=viewthread&tid=156810&extra=

**Comment by zoze0** [comment]
https://github.com/licardoY/corefile

 coredump文件

**Comment by SHIHUAMarryMe** [comment]
@licardoY 好的我现在开始试试.

刚刚试了试 coredump产生的文件可能由于cpu差异之类的/也可能是别的原因在我这里无法打开.
这样吧,你呢:
1, sudo coredumpctl list(这一步查看你系统上面所有崩溃过的应用, 而且你可以看到他们的PID).
2, sudo coredumpctl gdb PID(崩溃了的进程的过去的PID).
3, 此时肯定位于gdb调试状态了. 输入: r. 然后就会停止到崩溃的地方.
4, 输入: bt. 
5, 复制输出的信息给我就好了.

**Comment by licardoY** [comment]
`2018-05-23, 17:08:58.588 [Debug  ] [dfilemenumanager.cpp DFileMenuManager::actionTriggered   1012] "标记信息" "标记信息"

Thread 1 "dde-file-manage" received signal SIGSEGV, Segmentation fault.
0x00007ffff433ac8b in _int_malloc (av=av@entry=0x7ffff465bb00 <main_arena>, bytes=bytes@entry=120) at malloc.c:3387
3387	malloc.c: 没有那个文件或目录.
(gdb) bt
#0  0x00007ffff433ac8b in _int_malloc (av=av@entry=0x7ffff465bb00 <main_arena>, bytes=bytes@entry=120) at malloc.c:3387
#1  0x00007ffff433cf34 in __GI___libc_malloc (bytes=120) at malloc.c:2928
#2  0x00007ffff5439035 in QArrayData::allocate(unsigned long, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff5ba3bf7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#4  0x00007ffff5ba0cab in QTextFormat::setProperty(int, QVariant const&) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#5  0x00007ffff69a98c4 in Dtk::Widget::DCrumbTextFormat::setBackground(QBrush const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#6  0x00007ffff69a99e9 in Dtk::Widget::DCrumbTextFormat::DCrumbTextFormat(int) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#7  0x00007ffff69aa413 in Dtk::Widget::DCrumbEdit::makeTextFormat() const () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#8  0x00007ffff69aa4ec in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#9  0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#10 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#11 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#12 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#13 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#14 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#15 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#16 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#17 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#18 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#19 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#20 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#21 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#22 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#23 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#24 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#25 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#26 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#27 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#28 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#29 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#30 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#31 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#32 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#33 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
#34 0x00007ffff69aa502 in Dtk::Widget::DCrumbEdit::appendCrumb(QString const&) () at /usr/lib/x86_64-linux-gnu/libdtkwidget.so.2
---Type <return> to continue, or q <return> to quit---
`

**Comment by zoze0** [comment]
coredumpctl 找不到命令,不知道要安装哪个软件.  
使用gdb 后不会强退, 会卡死. 上午在论坛已经回复了

**Comment by BLumia** [comment]
coredumpctl 在 [systemd-coredump](https://packages.debian.org/sid/systemd-coredump) 包内。
贴log的时候用 \`\`\` 包裹住你的log，或者通过点击编辑框的 Insert Code 选项贴 log 可以防止被转义（上面被 reference 到别的 issue 了...）

**Comment by zoze0** [comment]
是点的insert code ,他是 `` . 这个功能我也用不到,或许别人没有这个bug.你们慢慢找吧.
