### ISSUE TITLE
scrolling is not smooth in a folder which contains different types of files

### ISSUE THREAD

**Issue by MetaiR** [linuxdeepin/dde-file-manager#14]
you can see and feel it better with this gif
at the first, I opened up a folder contains just other folders and then my download folder to show the difference

![deepin-screen-recorder_dde-file-manager_20180527065543](https://user-images.githubusercontent.com/7807264/40581935-5026e096-617b-11e8-8e1e-896dd017b97c.gif)

**Comment by BLumia** [comment]
@zccrs

**Comment by MetaiR** [comment]
nothing?

**Comment by zccrs** [comment]
Thank you, this issue has been fixed, waiting for the next release.
commit: 1790eef092877f7f81781b7412ec6776628843c0

**Comment by MetaiR** [comment]
@zccrs 
ممنونم
it means I'm thankful

**Comment by zccrs** [comment]
@MetaiR You are welcome, You well take it in Deepin 15.6 Release

**Comment by MetaiR** [comment]
yeh, my distro (manjaro) updated yesterday, I am using it right now and it's very smoother now
