### ISSUE TITLE
In flatpak?

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#15]
Can you please release a flatpak version of dde-file-manager ?

**Comment by zccrs** [comment]
I'm sorry, I don't understand why you need a flatpak version of the file manager

**Comment by SiamSami** [comment]
To install it easily on other Linux distributions.

**Comment by BLumia** [comment]
A flatpack package has limitation about accessing your file system, so it's totally useless if a file manager application can not even access your file system :joy:

**Comment by SiamSami** [comment]
OOPS!! Sorry, I didn't know about that.

**Comment by BLumia** [comment]
Gotta close this issue, feel free to reopen it if you have any other problem with this issue :)
