### ISSUE TITLE
Image information

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-file-manager#16]
Normally, in all desktops we can get information about image: width and height; but it is not possible in `Deepin`, why?

**Comment by BLumia** [comment]
> but it is not possible in Deepin

It **is** possible, but we don't have this feature yet.

btw, where did you like to let `dde-file-manager` display extra properties like this?

**Comment by SalahAdDin** [comment]
@BLumia All managers show that in bottom side(aside with weight, well,).

**Comment by BLumia** [comment]
Sorry idk about all managers did that, I checked dolphin (from kde) and nautilus (from gnome), both of them don't even have a bottom bar, but they got their place to display such extra properties like the properties dialog (nautilus) and the search result view (dolphin). Maybe you means the behavior what windows' `explorer.exe` does ? Hope you can leave a screenshot of the file manager app what you are using.

We currently don't have a plan about adding this feature, but maybe it will be added in future. So any feature is welcome and we will record and consider about the feature requests.

**Comment by zccrs** [comment]
Hi.
Thank you for your feedback. You can view the “width” and “height” information of the image through the image preview (Press the "Space" key)
