### ISSUE TITLE
文管任务缩略图点击不能切换窗口

### ISSUE THREAD

**Issue by dong8yong8** [linuxdeepin/dde-file-manager#17]
如题，开了多个文管的话，在任务栏点击缩略窗口的时候不能切换

**Comment by BLumia** [comment]
这个似乎不是文件管理器的问题。 @kirigayakazushin 
以及我这边是正常的...

**Comment by zccrs** [comment]
您好，文件管理器出现这样的问题时，其它程序有同样的问题吗，例如“深度终端”等

**Comment by BLumia** [comment]
由于的确不是文管的问题以及长时间没回复，这 issue 我先关了... 

如果遇到这个问题建议把 issue 提到 [Developer Center](https://github.com/linuxdeepin/developer-center/issues/) ，会帮你把问题定位到对应的项目。

**Comment by justforlxz** [comment]
也许是dock的问题。
