### ISSUE TITLE
[Arch Linux]第三方应用调用打开文件窗口，双击文件为打开

### ISSUE THREAD

**Issue by dongfengweixiao** [linuxdeepin/dde-file-manager#17]
使用 Qt 编写程序，当调用 “QFileDialog::getOpenFileName” 打开一个打开文件对话框，且双击企图选中某文件时，为打开该文件（调用文件格式对应的应用程序）。

**Comment by dragondjf** [comment]
已经修复了，1.4版本明天正式发布，请关注，谢谢
