### ISSUE TITLE
关于默认打开方式的bug

### ISSUE THREAD

**Issue by wszqkzqk** [linuxdeepin/dde-file-manager#18]
如题，将.docx文件的默认打开方式先设置为压缩管理器，再改回WPS Office，会仍然显示zip图标。
所以，默认打开方式的配置文件在哪里？
或者可不可以在文件管理器内增设一个一键重置默认打开方式。

**Comment by BLumia** [comment]
文件管理器的图标是根据文件的MIME类型来决定的，而不是关联的程序，所以其实你设置成WPS不会导致文件的图标变更。请问你所用的是 Deepin File Manager （深度文件管理器）吗？如果是，还希望可以提供更多信息以便复现 bug 。

另外，我们目前（1.7）使用的是 `gvfs-mime` 来设定文件关联的，除了使用文件管理器内建的右键菜单来设置默认打开方式之外，也可以通过 `gvfs-mime` 或 `xdg-mime` 来设置打开方式。

---------

Update: `gvfs-mime` 已被废弃，请使用 `gio mime`

**Comment by BLumia** [comment]
很久没有回复并且我们没法复现，就先关闭了。如果您依然有该问题并且能提供更多的相关信息，可以重新打开该 issue 并提供更多信息以便我们帮助您处理问题。
