### ISSUE TITLE
File manager column sort not sticking ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-file-manager#19]
Hi,

File Manager Ver. 1.7

after the last update the file manager is no longer saving the folder sorting view ... i like to keep things sorted as per 'Time Modified' latest first ... but every time file manager is opened the setting is reset to default 'Alphabetical sort'

It would be nice if Deepin file manager too had a Windows like every folder specific settings with regard to sort, icons view, etc ...

thank.s

**Comment by BLumia** [comment]
Hi,

Thank you for your feedback.

In the current (1.7) dde-file-manager behavior, if you just did click the table header, the view did changed but it's only for temporary change. We do save your sorting view but only when you select the sort order in your **right click context menu**.

glhf

**Comment by aiamuzz** [comment]
> Hi,
> 
> Thank you for your feedback.
> 
> In the current dde-file-manager behavior, ff you just did click the table header, the view did changed but it's only for temporary change. We do save your sorting view but only when you select the sort order in your right click context menu.
> 
> glhf

I am sorry its a failed implementation ... that sort will force Alphabetic sort for Name(reverse is not possible) ... similarly 'Time modified' works only in Ascending (the latest first(descending) is not possible) ... these implementations are steps in the backward direction ... 

really miss the old implementation ... as simple as clicking on the column label and the setting sticks(saved) ...

**Comment by BLumia** [comment]
@zccrs 

btw for a temporary workaround, after you change the sort order rule, select the sort order in the right click context menu again to save it.

**Comment by zccrs** [comment]
Hi,
You can view the “width” and “height” information of the image through the image preview (Ctrl+Space)

**Comment by aiamuzz** [comment]
> Hi,
> You can view the “width” and “height” information of the image through the image preview (Ctrl+Space)

@zccrs  ... i think you posted a wrong message to this issue thread.

We are discussing the 'sort' option of files and folders ... by clicking on the desired column label we intend to sort ... as this preference is not getting saved permanently like it used to in the previous version.

We request you to revert back the old implementation.

thank.s

**Comment by zccrs** [comment]
@aiamuzz 
Hi,
Thank you for your feedback.
We will consider revert the change of it in 1.8 release.

**Comment by aiamuzz** [comment]
> btw for a temporary workaround, after you change the sort order rule, select the sort order in the right click context menu again to save it.

it didn't work the way you suggested ... **selecting the sort order from right click the second time reverses the order and saves it** ...

I hope this complicated maneuver is going to be simplified back to the old method of clicking on the Column Label to achieve the desired order and the same is saved in settings effectively.

@zccrs ... is it possible to have a folder specific sort and view (like you have in WindowsOS) ...

**let me tell you the use case for a folder specific view and sort** ... _(while i may like the default view across all folders to be a 'list view' and sort setting to show 'latest files and folder showing on top')_

I have particular folders where i store images/photos ... i would like such folders to display items in an **'icon view'** with its **'own separate sort preference'**, this way it will be easier to scroll through the photographs and find the photo/image we were looking for.

Can we hope to see a folder specific separate "View & Sort settings" ???

**Comment by aiamuzz** [comment]
@BLumia ... @zccrs  ...

Ok i have done some more testing ... and have observed the following ... please do consider this before you revert the changes ...

throughout my usage on DeepinOS ... i have never used the 'right-click' sort option except when suggested by you people as temporary workaround.

Throughout my DeepinOS experience from last year ... i never felt the sort settings worked differently for each folder ... hence my last post requesting you to have folder specific sort settings.

turns out i was wrong or its something you've implemented recently ... back to the point ... my current 'right-click' sort selection testing suggests that there is already a **'folder_specific_sort_setting'** in place ...

now if you could consider adding a **'folder_specific_view_setting'** ... that would take care of the use case for images/photos folders.

**Comment by aiamuzz** [comment]
@BLumia ... @zccrs  ...

May be i am being a little greedy here ... but anyways let me leave that to you ... but i see an opportunity here ...

'Click on the Column label' ... to sort the folder contents to your preference, at this point, the setting gets stored for that particular folder.

This issue led me to think on it a little more and the possibility it leads to ...

How about having a ... **'temporary sort setting' and a 'permanent sort setting'**

**'temporary sort setting' -** is already in place with the original issue reported(clicking on the column-label) not sure if it was intended by design or its an unexpected situation ... come to think of it, its actually working as a temporary sort option which is nice in a way ... when you are trying to momentarily/occasionally look for a particular file/folder.

**'permanent sort setting' -** again this too is already in place when sort is selected from the 'right-click' menu.

so actually i am getting best of both worlds ... only that its not elegant enough for the user to effectively use it ...

**So if you see what i am saying ... then this situation could be played to an advantage which will result in  dual sort option (temporary and permanent)** ... if only done in an elegant way.

**Comment by aiamuzz** [comment]
> @aiamuzz
> Hi,
> Thank you for your feedback.
> We will consider revert the change of it in 1.8 release

If you are willing to explore the temporary & permanent sort options then you may have to hold off on reverting the change ... i do have an elegant way to implement both.

**Comment by aiamuzz** [comment]
What if you let me click the 'Column Label' with the 'Ctrl key' held down ?

If I press **'Ctrl + Column Label click'** to sort, this could be linked to the action of sorting when invoked from the **'right-click'** menu which i am using as a temporary workaround ... this could in fact serve as the **'Permanent Sort setting'** for a given folder.

The current **'Column Label click'** which is not getting saved currently can serve as the **'Temporary Sort setting'** 

Please run this by your project manager ... and see if the idea sells ...

Cheers.

**Comment by aiamuzz** [comment]
> @aiamuzz
> Hi,
> Thank you for your feedback.
> We will consider revert the change of it in 1.8 release.

**@BLumia & @zccrs**  ... might want to hold off on the reverting of the current implementation !!!

after using it for the last couple of days ... i am liking the idea of a permanent sort setting(through the right click menu) and a temporary sort setting (through a click on the column labels) ...

**If only you could match the Ctrl + column lable click event to the right click sort selection ... it would be just perfect and elegant to use it and easy for the user to understand the 2 state sort setting for each folder !!!**

**Comment by BLumia** [comment]
Hi,

Since v1.7 is a already released version so we could only make it into next release, we are planning to revert it. So please patient 😛.

Thanks

**Comment by aiamuzz** [comment]
> Hi,
> 
> Since v1.7 is a already released version so we could only make it into next release, we are planning to revert it. So please patient stuck_out_tongue.
> 
> Thanks

sorry ... i am not being impatient ... i think you did not understand ... 

**PLEASE DO NOT REVERT !!!
LET THE CURRENT IMPLEMENTATION CONTINUE, ITS PERFECT !!!**

 you can close this issue !!!

**Comment by BLumia** [comment]
This issue will be closed after we decided the operate of this behavior and implement it. We will consider about it, thanks anyway!

**Comment by aiamuzz** [comment]
fair enough ... :)

**Comment by BLumia** [comment]
Hello and we've decided to revert this behavior back to the old one (will remember sort order right after you click the table header), and this behavior will be back in v1.8 release.

[See this commit if you are interested about code](https://github.com/linuxdeepin/dde-file-manager/blob/77beba0cfec27ea5cad3755a15556eef82ae75b9/dde-file-manager-lib/views/dfileview.cpp#L1302)

Since many user (like you) will be confused by the current behavior and don't know how to save the sort order, and Shfit + Click is still a not very direct-viewing approach, so we decided to revert to the old behavior.

If you have any other issue about this, feel free to reopen this issue :)

**Comment by aiamuzz** [comment]
@BLumia  ....

Shift + Click or Ctrl+Click ... should work ... anyways its your decision !!!

But i can confirm that the current implementation has its advantages as i have been using both permanent and temporary sort orders ... and i am enjoying it to be honest !!!

In the current setup of temporary and permanent sort orders registered separately, I CAN CONFIRM WITH CONFIDENCEE that i am using the sort feature more freely ... as i am assured that my permanent sort order is set ... and my last use of sort (by clicking on the column labels at that instance) is discarded ... This has pushed up my using the sort method far more frequently than ever !!!

Discarding the current implementation completely is not recommended ... you may want to sleep over it ... The confusion that you are talking about can easily be countered by a 'mouse-over' message pop-up will kill the confusion !

I am a little busy right now ... But i'll try to show what i mean with a screenshot shortly ... if you can bear with me.

:)

**Comment by aiamuzz** [comment]
@BLumia ... @zccrs  ... 

I found some time in between work ... please find a suggestion on how the whole confusion can be resolved by this simple implementation with graphical markers.

This way the feature can be highlighted as a first across all operating systems (Windows Mac or any other linux distro's)

![ctrl click sort method](https://user-images.githubusercontent.com/3283676/41969562-72af0f72-7a25-11e8-8ce7-d4e32c2f69a4.png)

Please note that i have described the process flow from the point of introducing such a feature as well as a simple process flow for the user to effectively use this great feature !!!

Let me remind you this feature is already functional under the hood(coding is in place) only the process/use flow has to be smoothed out ... and this image should help you do exactly that. 

you can take it to your project manager and UI designer and discuss it out ...

**Comment by aiamuzz** [comment]
My intentions are not to impose ... but just that i don't want a good idea being withdrawn (when the coding, hard part is already in place) just because a process flow or use-case flow is confusing ... hence the extra effort in trying to explain things as above graphically !!!

As you can see in the above image, A feature you have already coded can actually work without any confusion !!!
