### ISSUE TITLE
Any way to use it on ubuntu or any other debian based distro??

### ISSUE THREAD

**Issue by Bearbobs** [linuxdeepin/dde-file-manager#191]
tl,dr: Please submit your issue to [Developer-Center](https://github.com/linuxdeepin/developer-center/issues/) instead of here.

To make issue tracking more effective, we decided to move our issue board to [Developer-Center](https://github.com/linuxdeepin/developer-center/issues/), so please submit your bug report, feature request or other issue directly to [Developer-Center](https://github.com/linuxdeepin/developer-center/issues/), and you can also tracking these issue in the [projects](https://github.com/orgs/linuxdeepin/projects) page if you're interested.

**Comment by BLumia** [comment]
tl,dr: Please submit your issue to Developer-Center instead of here.

Please also do a search first: https://github.com/linuxdeepin/developer-center/issues/733
