### ISSUE TITLE
#问题 图片预览不支持jpg格式

### ISSUE THREAD

**Issue by mymartin** [linuxdeepin/dde-file-manager#2]
jpg文件预览效果如图，png格式文件能够正常预览。

![image](https://user-images.githubusercontent.com/6276117/37645184-127dbf34-2c61-11e8-891a-6d6cc5e18504.png)

**Comment by epoiate** [comment]
I don't have this issue with version 1.6.2 on Arch as in the picture below.
![deepin screenshot_selecionar area_20180327023727](https://user-images.githubusercontent.com/6474351/37948727-d27e4852-3167-11e8-86eb-1859498bd54a.png)

**Comment by mymartin** [comment]
maybe it's something wrong.
but the thumbnail shows correctly when I change the jpg to other format like png.
I think it's not a problem. And other jpg running well.

**Comment by zccrs** [comment]
你好，有可能是这个文件的格式识别错误导致的，尝试把 “大马确认函.jpg” 改成 "大马确认函.png" 试一下能否预览

**Comment by BLumia** [comment]
现在应该即便扩展名不正确也能够正确预览图像了，如果依然有问题，可以重新打开该 issue 并提供更多信息（比如不能预览的原图文件）帮助确认问题。

--------

Now it should always works whatever the suffix is correct. If you still got this issue, feel free to reopen this issue and provide more details (like the file which caused preview failed) to help us find out the bug.
