### ISSUE TITLE
dde-filemanager not following gtk-theming

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-file-manager#2]
![](http://imgur.com/52XtVakl.png)

**Comment by fasheng** [comment]
deepin filemanager wrote by Qt, maybe it's the reason~

**Comment by oberon2007** [comment]
Well I have already in **/etc/environment**:
```
QT_STYLE_OVERRIDE='gtk2'
QT_QPA_PLATFORMTHEME='qt5ct'
```
and used **qt5ct** to set theming to gtk2.
Other qt-apps like fore example **vlc** are looking fine.

**Comment by fasheng** [comment]
Ehmm, maybe all the widgets were customized, so filemanager just dropped the system themes..
@iceleaf916

**Comment by oberon2007** [comment]
hm. that would be bad news, indeed...

**Comment by iceleaf916** [comment]
As I know the series applications of Deepin were customized with Deepin's UI widgets. And it will use Deepin's design theme in the later future.

**Comment by oberon2007** [comment]
So that means we will have only one theme available and no customization will be possible?

**Comment by Rekols** [comment]
DDE-filemanager is developed with QT, so do not inherit the GTK+......

**Comment by bigbruno** [comment]
Deepin apps not use qt themes, dde-file-manager use internal theme and not possible change.

**Comment by manateelazycat** [comment]
Deepin application will follow deepin's theme standard, just ignore system gtk/qt theme.

**Comment by manateelazycat** [comment]
No, deepin application will provide a way to switch to theme, but it won't follow gtk theme.

**Comment by Skillzore** [comment]
Why is this closed? Deepin file manager still doesn't have any theme settings or follow and themes applied...

**Comment by patrickelectric** [comment]
Fresh install on archlinux, theme isn't applied.
