### ISSUE TITLE
Typo error in replace button

### ISSUE THREAD

**Issue by 24aitor** [linuxdeepin/dde-file-manager#20]
The text of the Replace button is incorrect because it shows 'Repalce' as can you see in screenshot below.

![deepinscreenshot20170311134748](https://cloud.githubusercontent.com/assets/20477883/23823471/ba67ab9e-0663-11e7-90b8-6f8ae658a0b2.png)

I am on manjaro linux.

**Comment by dragondjf** [comment]
ok ,thanks for your feedback; it has been fixed in 1.4 release version.
