### ISSUE TITLE
Cannot perform cut,copy and paste for multiple files . Application exits itself .

### ISSUE THREAD

**Issue by arjunkravi** [linuxdeepin/dde-file-manager#20]
I use deepin 15.6 DE in Manjaro 17.1.10 Community Edition . I was very satisfied with default file manager but when the topic went to heavy task such as basic file operations in dde-file-manger , it terminates itself with whole open windows . Now I use Caja file manager as alternative . I really love DDE-file-manger , Can anyone help me with it ? Thanks in advance .

**Comment by BLumia** [comment]
It should works... Could you provide more information like the error log and the dde-file-manager version?

Log locate at: `~/.cache/deepin/dde-file-manager/dde-file-manager.log` (you can paste log to [here](https://paste.ubuntu.com/) and leave a link here)
Get version: `pacman -Qi dde-file-manager`

Thanks

**Comment by BLumia** [comment]
We had refactored the part of code about doing multiple file operations, if you got any issue about this before, please also check if the most recent release (v1.8) can solve your issue or not.

If you still got problem, feel free to open up another issue with more details provided, thanks.
