### ISSUE TITLE
compress, extract here and extract doesn't work

### ISSUE THREAD

**Issue by Chathula** [linuxdeepin/dde-file-manager#21]
i am using manjaro deepin. when i click extract here or extract or compress on deepin file manager, it doesn't do anything... how to fix it!

(i can't update deepin file manager, if i do it will crash the whole file manager. i tried once. i don't want to try it again. is there any symbolic link  fix? )

**Comment by oberon2007** [comment]
It looks like noone is looking at the filemanager issues issues here at all... Who is in charge or where should we inquire about these problems @dragondjf @hualet @jouyouyun @sbwtw ?

**Comment by oberon2007** [comment]
Is Deepin expecting a certain archiver application to be installed? Or can the default archiver application be configured anywhere? @felixonmars ?

**Comment by hualet** [comment]
@dragondjf  is in charge.

**Comment by oberon2007** [comment]
Thank you @hualet 👍 
I've figured it out myself finally after digging through the source code for a while:
You need to install **file-roller**. So this should actually be a dependency or at least an opt-depends. I've added a task at archlinux-packages :)

**Comment by hualet** [comment]
Well...OK, since file-roller is preinstalled in our ISO, so it's hard to find that the runtime dependency is missing :smile:  Thanks, anyway.

**Comment by oberon2007** [comment]
Yes, but then also someone has decided in the first place to hard-code file-roller into dde-file-manager... 😉 I think it should be listed with the other dependencies in the README. :)

**Comment by hualet** [comment]
Yeah, sure @zccrs
