### ISSUE TITLE
How to add entry to context menu?

### ISSUE THREAD

**Issue by damien122** [linuxdeepin/dde-file-manager#21]
Hi,
I want to kow how to add an entry to the context menu in the file manager.
Espacially I want to add "Open with Visual Studio Code" to already opend folder like the entry "open Terminal" allready did.

**Comment by BLumia** [comment]
There are two ways to do this.

You can create a simple json file locate at `~/.config/deepin/dde-file-manager/menuextensions/` to extend the context menu. For example, create a `vscode.json` and leave the content as:

``` json
[
    {
        "MenuType": "EmptyArea",
        "Icon": "Files",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en_US]": "Open with VSCode",
        "Exec": "code"
    }
]
```

**↑ This can be used in the current released version (1.7) ↑**

By the way, the currently released version of `dde-file-manager` have some problem about the json menu extension's implementation, i.e. we only accept a `Exec` key for custom the executable name, but user can't custom the argument, and it won't set the working directory for the created process. In the next release, we will add a `Args` key for custom the execute arguments and set the current directory which you created the context menu as the working directory like this.

``` json
[
    {
        "MenuType": "EmptyArea",
        "Icon": "Files",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en_US]": "Open with VSCode",
        "Exec": "code",
        "Args": ["."]
    }
]
```

**↑ This will only works under `dde-file-manager` version 1.8^ ↑**

So a temporary workaround is write a middle-ware script like `code.sh` , set the `Exec` key to your `/path/to/code.sh` and let that script help you launch `code`.

Another way to do menu extension is write a custom menu extension plugin, but currently we only have Chinese version of document (document improvement WIP now), you can check the document out [here](https://cdn.rawgit.com/linuxdeepin/dde-file-manager/e8bd4a23/doc/Menu%20Plugins%20and%20Extensions(%E6%96%87%E4%BB%B6%E7%AE%A1%E7%90%86%E5%99%A8%E6%89%A9%E5%B1%95%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95%E7%9A%84%E4%B8%A4%E7%A7%8D%E6%96%B9%E5%BC%8F).html) .

Hope it helps, leave a comment if you got any further questions :P

**Comment by damien122** [comment]
Hi @BLumia,

thanks for your answere. Unfortunatelly your fix works not propperly.
I have added this code:
```
[
    {
        "MenuType": "EmptyArea",
        "Icon": "Files",
        "Text[de]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "Exec": "code"
    },
{
        "MenuType": "SingleDir",
        "Icon": "Files",
        "Text[de]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "Exec": "code"
    },
{
        "MenuType": "MultiFileDirs",
        "Icon": "Files",
        "Text[de]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "Exec": "code"
    }
]
```

But my Context menü entry is empty, by the way my system language is German (de).
Also the behavior of VSCode is strange. If I start VSCode from a selected folder or file, I just see an empty file with the file name but no contetent. Is this because of the missing Args? 

What I also tried was:

```
[
    {
        "MenuType": "EmptyArea",
        "Icon": "Files",
        "Text[de]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "Exec": "'code ./'"
    }
]
```


In my understanding the exec command is just an executable which is triggerd. My idea was to encapsulate the command with single quotes. Unfortunatelly this fix didn't work. Do you maybe know an workarround?

**Comment by BLumia** [comment]
As I mentioned above, the current implemention (v1.7 of dde-file-manager) has some weird behavior, you can only set a executable program name in the `Exec` key, the file manager will launch the executable program with fixed arguments which is not customizable and VSCode did nether recognize the args. So the solution is write a helper script to process the argument and launch VSCode in your helper script.

``` json
[
    {
        "MenuType": "EmptyArea",
        "Icon": "Files",
        "Text[de_DE]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Exec": "/path/to/your/launch-vscode.sh"
    },
    ......
```

We will allowed custom args in the next release (already got this feature in the develop2.0 branch now). so in **next version (v1.8)** you can use `"Args": ["."]` and it will help you launch VSCode as well.

You can close all `dde-file-manager` instance and launch it from terminal, then when you are clicking at the custom context menu you created by the json, you can see some useful debug info from `stdout`.

btw about why your context menu entry is empty, maybe you can try to change the local index as `de_AT`, `de_DE` or something like this. (we use [`QLocale::name()`](https://doc.qt.io/qt-5/qlocale.html#name) as the index string.)

**Comment by damien122** [comment]
Ok thanks I will wait for the next release or try the debug infos to create a helper script.
The local change to `de_DE` did the job and the entry shows now also text, thanks :)
Do you have some information when the release 1.8 will be?

**Comment by BLumia** [comment]
I'm not sure when will we release it, but you can try out the current development version here: [snapshot of 5285ed3 on develop2.0 branch](https://ci.deepin.io/job/dde-file-manager/4861/artifact/) .

At least you need to install the `dde-file-manager` and the `libdde-file-manager` package, recommended to install all of them or try build from source by yourself.

It should be functional but it's still a under development version, just a reminder.

**Comment by BLumia** [comment]
Gotta close it, feel free to reopen it if you got any future problem about this issue :)

**Comment by damien122** [comment]
@BLumia I got today my update to file manager 1.8 and the args parameter works now fine. But unfortunately the "SingleFile" selection don't work. It opens my home directory in vscode instead. I try to add MimeType and Suffix but it changed nothing. As much as I can see is that the file is not hand over as argument. How can I hand over the selected file as Argument?

Here is my config:
```
[
    {
        "MenuType": "EmptyArea",
        "Icon": "/home/damien/.config/deepin/dde-file-manager/menuextensions/Visual_Studio_Code_0.10.1_icon.png",
        "Text[de_DE]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "Exec": "code",
        "Args": ["."]
    },
	{
        "MenuType": "SingleDir",
        "Icon": "/home/damien/.config/deepin/dde-file-manager/menuextensions/Visual_Studio_Code_0.10.1_icon.png",
        "Text[de_DE]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "Exec": "code",
        "Args": ["."]
    },
	{
        "MenuType": "MultiFileDirs",
        "Icon": "/home/damien/.config/deepin/dde-file-manager/menuextensions/Visual_Studio_Code_0.10.1_icon.png",
        "Text[de_DE]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "Exec": "code",
        "Args": ["."]
    },
	{
        "MenuType": "SingleFile",
        "Icon": "/home/damien/.config/deepin/dde-file-manager/menuextensions/Visual_Studio_Code_0.10.1_icon.png",
        "Text[de_DE]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "MimeType": "text/plain;text/md",
        "Suffix": "md;conf;py;sh;cs",
        "Exec": "code",
        "Args": ["."]
    },
	{
        "MenuType": "MultiDirs",
        "Icon": "/home/damien/.config/deepin/dde-file-manager/menuextensions/Visual_Studio_Code_0.10.1_icon.png",
        "Text[de_DE]": "Mit VSCode öffnen",
        "Text[zh_CN]": "在 VSCode 中打开",
        "Text[en]": "Open with VSCode",
        "Exec": "code",
        "Args": ["."]
    }
]

```

**Comment by BLumia** [comment]
> But unfortunately the "SingleFile" selection don't work.

Your `Args` key use `["."]` , that means launch vscode and pass a "." as argument, i.e. it will run `vscode .` from your current working directory.

I personally recommend you write a custom `.desktop` file for this requirement. Check out [the spec](https://standards.freedesktop.org/desktop-entry-spec/latest/) to know how to write your own `.desktop` file.

**Comment by damien122** [comment]
ok, thanks I will try :smiley:

**Comment by nij4t** [comment]
How do you get target filename to pass it to your exec command as an argument?

**Comment by BLumia** [comment]
> @aspartame21: How do you get target filename to pass it to your exec command as an argument?

Currently you can't (you can use "exec" to run your helper script and parse arguments from your custom script tho), but if you are just want to add a new option for a type of file, you can create a custom `.desktop` file ([spec](https://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/)).

We can add support for passing file name with format like "%F", quite busy these days so priority will be not that high, patches are welcome :)

**Comment by alexandre1985** [comment]
The "%F" would be great, and would solve my problem.
Does somebody know how to make a application suggested to be open by any filetype/mimetype?

**Comment by diyhackers2015** [comment]
> The "%F" would be great, and would solve my problem.
> Does somebody know how to make a application suggested to be open by any filetype/mimetype?

MimeType=application/octet-stream

**Comment by BLumia** [comment]
Hello guys and here are some news.

If you are using Deepin lion or elephant (distro) and would like to create your own context menu entry, we recommend you install `dde-file-manager-menu-oem` package by simply typing `sudo apt install dde-file-manager-menu-oem`. Then you'll be able to use a more advanced way to create your own context menu entry which is very similar to [KDE's ServiceMenu concept](https://techbase.kde.org/Development/Tutorials/Creating_Konqueror_Service_Menus). It use the standard `.desktop` file spec so things like `%F` will also works.

For users who use DDE on other distro, you can also build [this plugin](https://github.com/linuxdeepin/dde-file-manager-menu-oem) by your own. In the next major version release of the dde-file-manager (should comes with v20 release), this new extension method will replace the old json format extension method so everyone can use it :)

**Comment by psycho-driver** [comment]
Here's an example of a bash script for working on a specific mimetype (flac, in my case).

My flac.json file in ~/.config/deepin/dde-file-manager/menuextensions
```
[
  {
    "MenuType": "SingleFile",
    "MimeType": "audio/flac;audio/x-flac",
    "Icon": "Files",
    "Text[en_US]": "Convert to VBR MP3",
    "Exec": "flac2mp3"
  }
]
```

My flac2mp3 shell script
```
#!/bin/bash

FULLPATH="$@"
TMPPATH=${FULLPATH:7}
FLACPATH=`dirname "$TMPPATH"`
FLACFILE=`basename "$TMPPATH"`
OUTFILE=`basename "$FLACFILE" .flac`

cd "$FLACPATH"

#zenity --info --text="$FLACFILE"
#zenity --info --text="$FLACPATH"
#zenity --info --text="${OUTFILE}.mp3"
#zenity --info --text="$PWD"

ffmpeg -i "$FLACFILE" -qscale:a 0 "${OUTFILE}.mp3"
```

I left the zenity comments in so you can see how to quickly debug your own scripts if they aren't working right.

**Comment by weslleystos** [comment]
Hi, this method doesn't work in deepin 20.2.3, I've tried many solutions but nothing working.
Please consider checking if still working...
