### ISSUE TITLE
Open with - passing arguments to custom script

### ISSUE THREAD

**Issue by axxox** [linuxdeepin/dde-file-manager#210]
Hello, is there a way to integrate *Open with* and *add other programs* with custom bash script? Are any arguments passed on execution?

I would like to make archives extract automatically (on double-clicked, OSX like behavior).
I've got `fast-extract.sh`
```sh
#!/bin/bash
file-roller -h $1
```
I works for bash execution, ex. `$ ./fast-extract.sh /path/to/file`
But when I'm add it as *Open with* and  *add other programs* - it opens only new filer-roller window.

**Comment by BLumia** [comment]
The generic way is write a custom `.desktop` file for it (you can run your bash script by editing the `Exec` key), then it will appears in the `Open with` menu so you can use it. See [desktop entry spec](https://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/) for more details :)

**Comment by axxox** [comment]
> The generic way is write a custom `.desktop` file for it (you can run your bash script by editing the `Exec` key), then it will appears in the `Open with` menu so you can use it. See [desktop entry spec](https://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/) for more details :)

Works like a charm! Thank you :)

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Exec=file-roller -h %f
Terminal=false
Name=FastExtract
Icon=application-x-desktop
MimeType=*/*
```
