### ISSUE TITLE
My dde-file-manager not reloading automatically!!

### ISSUE THREAD

**Issue by edsonboldrini** [linuxdeepin/dde-file-manager#220]
### I'm using Deepin 15.10.1 and every time I make some change on file or folder, the file manager not reload like it should do.

Examples: 
When I rename a file or folder, I can't see the item renamed when I finished, I have to push F5 to reload the folder and see the change. The same behavior happens when I move some file to another folder.

Does someone have an idea how to solve it?

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/developer-center/issues/1289

You may using some software which takes all your inotify amount like visual studio code or intellij idea. Consider tweak your `fs.inotify.max_user_watches` value up.

This repo no longer accept new issue (you may already know when you creating this issue), so closing..
