### ISSUE TITLE
dark theme has white border when window effects disabled

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/dde-file-manager#23]
As in the title. With compositing enabled the dark theme looks nice, but when compositing is turned off, it looks like this:

![screenshot_2018-07-03_23-52-24](https://user-images.githubusercontent.com/11800714/42246411-be35aa68-7f1c-11e8-92bc-c49a995260d1.png)

...not ideal :wink:

**Comment by alvarosamudio** [comment]
it was corrected in the latest versions
