### ISSUE TITLE
add Option to add Context Menu actions

### ISSUE THREAD

**Issue by jay-bricksoft** [linuxdeepin/dde-file-manager#23]
in ubuntu's nautilus it is possible to register custom context menu entries.
it would be great if deepin's filemanager had that feature too

**Comment by zccrs** [comment]
See：https://github.com/linuxdeepin/dde-file-manager/blob/develop2.0/doc/Menu%20Plugins%20and%20Extensions(%E6%96%87%E4%BB%B6%E7%AE%A1%E7%90%86%E5%99%A8%E6%89%A9%E5%B1%95%E5%8F%B3%E9%94%AE%E8%8F%9C%E5%8D%95%E7%9A%84%E4%B8%A4%E7%A7%8D%E6%96%B9%E5%BC%8F).html
