### ISSUE TITLE
Visual bug to renomer file using File Manager.

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxdeepin/dde-file-manager#24]
1. Problem/Advice description
Visual bug to renomer file using File Manager.
2. How to reproduce the problem
Visual bug to renomer file using File Manager.
3. Problem reproduce frequency
All time
Operating system :deepin
Desktop environment :dde

http://feedback.deepin.org/feedback/detail/2523

[deepin-feedback-cli-Deepin-15.4-all-20170328-185212.tar.gz](https://github.com/linuxdeepin/dde-file-manager/files/877384/deepin-feedback-cli-Deepin-15.4-all-20170328-185212.tar.gz)
![deepin-screen-recorder_select area_20170328201356](https://cloud.githubusercontent.com/assets/8754997/24432526/3e45a662-13f9-11e7-83ef-80a1cc2127c3.gif)

**Comment by zccrs** [comment]
Fixed in the latest version
