### ISSUE TITLE
Can't turn on "Share this folder"

### ISSUE THREAD

**Issue by shutterPL** [linuxdeepin/dde-file-manager#25]
Here is a GIF with my issue.
![deepin-screen-recorder_dde-file-manager_20180705191849](https://user-images.githubusercontent.com/40338330/42338109-0b48cb60-8089-11e8-833b-5880374a8ece.gif)

**Comment by BLumia** [comment]
You need `samba` package installed to use this feature. If you are using Linux Deepin, try `apt-get install samba`.

In next version we'll also add a hint message to ask user install `samba` when he/she are attempt to use this feature but samba not got installed.

**Comment by shutterPL** [comment]
@BLumia That solved my problem. Thanks!

**Comment by bubifengyun** [comment]
@BLumia not only `turn on`, you add  `hint message`; please add `warning message` when normal user turn off root's share folder. Thank you.
