### ISSUE TITLE
是否有弃用 qt5, 完全转向 qt6 的计划

### ISSUE THREAD

**Issue by wineee** [linuxdeepin/dde-file-manager#2517]
nixpkgs 移植无法接受一个包同时需要 qt5 和 qt6,  文管现在同时需要 https://github.com/linuxdeepin/dde-file-manager/blob/master/debian/control
是否有完全移除 qt5 依赖，只使用 qt6 的规划

**Comment by Johnson-zs** [comment]
很快就会全面适配Qt6.8
