### ISSUE TITLE
Theme doesn't change

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#26]
The theme of the file manager doesn't change even though theme of the other programs do.

Can you please fix it?

[EDIT] :
I am using Arch Linux. The version of the file manager is 1.7.
Also, I am trying to change the theme from deepin-settings and NOT from the file manager.

**Comment by BLumia** [comment]
Did you means when you toggle the theme from the file manager's menu, it doesn't works?

------

btw, please always leave more details like which distro you are using, which version of dde-file-manager you are using and how to reproduce the issue so it can be very helpful for us to reproduce the bug and fix it.

**Comment by SalahAdDin** [comment]
@SiamSami do you have `gnome-desktop` too in your OS?

**Comment by BLumia** [comment]
> I am trying to change the theme from deepin-settings and NOT from the file manager.

Hi and we are not yet supported to make the theme follow the system setting for now, but we are planning to add this feature in the future.

btw, please post a new comment rather than edit the old post if you are adding information so we can get a notification about that. thx :)

**Comment by ghost** [comment]
> > I am trying to change the theme from deepin-settings and NOT from the file manager.
> 
> Hi and we are not yet supported to make the theme follow the system setting for now, but we are planning to add this feature in the future.
> 
> btw, please post a new comment rather than edit the old post if you are adding information so we can get a notification about that. thx :)

@BLumia  Any ETA on when all the deepin programs will follow the systems themes?

**Comment by BLumia** [comment]
> Any ETA on when all the deepin programs will follow the systems themes?

Not sure, probably when 15.8 or 15.9 got released, right after all other deepin app got dark theme support.

**Comment by wangjia12** [comment]
@hualet @zccrs 你们有空自己做，不算在需求里面，开会讲的。

**Comment by alvarosamudio** [comment]
does not detect the 3G/4G USB modem

**Comment by xmine64** [comment]
hi. i'm using deepin 15.9 on arch.
dark theme toggle with file manager works, but the change theme in settings not working.
it changes icons and cursor but not gtk theme.

**Comment by BLumia** [comment]
> hi. i'm using deepin 15.9 on arch.
> dark theme toggle with file manager works, but the change theme in settings not working.
> it changes icons and cursor but not gtk theme.

Yeah dde-file-manager's theme setting is independent with the one in system setting currently.

If you means changing theme from the system setting can not change the theme for gtk apps, then it's a different issue. Feel free to open a new issue at [linuxdeepin/developer-center](https://github.com/linuxdeepin/developer-center/issues) ;-)

**Comment by SiamSami** [comment]
Since Deepin file manager doesn't support GTK themes, I think I should just close it then.

**Comment by ForeverZer0** [comment]
Pretty sure OP has the complaint that everyone else does about the theme for the file manager being hard-coded and not changing with the system's selected theme. For example, the file manager has either light or dark theme, there is nothing else.

### To reproduce
1. Install `deepin` and `dde-file-manager`
2. Attempt to make file manager theme **ANYTHING** other than the default "light" or "dark", feel free to use any typical means necessary that don't involve building it from source. 

### Expected behavior
Changing system theme changes the appearance of the file manager.

### What actually happens 
Absolutely nothing, it just goes on looking different that the rest of OS.

This issue is rather critical and seems to be getting ignored. It seems to be the chief complaint with every review on the web, and is always answered with some (intentional?) confusion and misunderstanding when brought up to developers, as if they somehow unaware that this issue even exists.

**Comment by BLumia** [comment]
> Pretty sure OP has the complaint that everyone else does about the theme for the file manager being hard-coded and not changing with the system's selected theme. For example, the file manager has either light or dark theme, there is nothing else.
> 
> ### To reproduce
> 1. Install `deepin` and `dde-file-manager`
> 2. Attempt to make file manager theme **ANYTHING** other than the default "light" or "dark", feel free to use any typical means necessary that don't involve building it from source.
> 
> ### Expected behavior
> Changing system theme changes the appearance of the file manager.
> 
> ### What actually happens
> Absolutely nothing, it just goes on looking different that the rest of OS.

Well, the theme selection from control panel actually only control GTK application theme, DTK is not based on GTK so changing theme via that place will not change the DTK application appearance. The "Light" and "Dark" is also just a theme name, The list can be much more longer if you install more GTK themes:

![image](https://user-images.githubusercontent.com/10095765/58412404-f5e81700-80a8-11e9-9205-aa668ce22a45.png)

> This issue is rather critical and seems to be getting ignored. It seems to be the chief complaint with every review on the web, and is always answered with some (intentional?) confusion and misunderstanding when brought up to developers, as if they somehow unaware that this issue even exists.

Nope, actually we have plan about implement global DTK theme selection support in the future updates, but the priority is lower than what we current are working on. We mainly track our issue in [Developer Center](https://github.com/linuxdeepin/developer-center/issues) btw.
