### ISSUE TITLE
Many segfaults and error messages in logs caused by dde-file-manager

### ISSUE THREAD

**Issue by michalzubkowicz** [linuxdeepin/dde-file-manager#27]
Distro: Deepin linux, newest

In dmesg i see many segfaults caused by dde-file-manager:
dde-file-manage[4200]: segfault at 20 ip 00007f7ba85dd2ec sp 00007fff7db78a40 error 4 in libQt5Core.so.5.6.1[7f7ba84a9000+4af000]
[27658.548870] dde-file-manage[4220]: segfault at 20 ip 00007f30b691c2ec sp 00007ffe892e84c0 error 4 in libQt5Core.so.5.6.1[7f30b67e8000+4af000]
[27668.546701] dde-file-manage[4239]: segfault at 20 ip 00007ff64db362ec sp 00007ffc9aa7fcb0 error 4 in libQt5Core.so.5.6.1[7ff64da02000+4af000]

Logs are fullfilled with errors also:
Jul 12 20:07:47 tx com.deepin.filemanager.daemon[4269]: 2018-07-12, 20:07:47.862 [Debug  ] [main.cpp             main                                53] FileManagerDaemon(0x55ffcbd316c0)

**Comment by BLumia** [comment]
Not sure about what's the problem about this issue and how to reproduce the issue. Is there something wrong with the dde-file-manager like the UI behavior or functionality which associate with this log?

btw, install the dbgsym package so we can get more useful debug log.

**Comment by michalzubkowicz** [comment]
It's reproducing all the time from system start logs are and dmesg is filled with this. 

There is no error from UI side nor nothing strange happens. 
I've installed package dbgsym for dde-file-manage, but there is nothing in /usr/lib/debug

**Comment by BLumia** [comment]
We'll do some code cleanup to reduce the debug log (we are already working on that) and some existed bugs should also be fixed in future updates. That'll reduce this kinds of output fill out the system log and dmesg. Hope that helps. 

If you got any further questions, feel free to reopen this issue :)
