### ISSUE TITLE
qmake问题

### ISSUE THREAD

**Issue by pptfz** [linuxdeepin/dde-file-manager#272]
qmake ..  无法成功执行，卡住好几个小时都不动是怎么回事

**Comment by BLumia** [comment]
如果你是获取的master最新源码编译的话肯定是编不过的，当前（2020/03/27）master 的代码其实是 v20 的版本，依赖其它 v20 的包，但其它 v20 的包均没放出来，所以编不过的。如果希望编译的话，你需要切到你对应发行版所包含的 tag 上再进行编译，或者直接拉取你发行版所使用的对应源码版本。

顺便，提供更多信息是个好习惯，请考虑在反馈问题时提供更多有助于判断问题的信息，例如你所使用的发行版，你获取的源码版本，你所使用的 Qt 版本，报错提示等。

**Comment by pptfz** [comment]
好的，非常感谢🙏
