### ISSUE TITLE
File manager cannot open my S6 Edge phone while Nautilus can

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-file-manager#28]
I'm trying to open my cell phone in the `deepin`'s default file manager and I get this:
![deepin-screen-recorder_desktop_20180717092108](https://user-images.githubusercontent.com/5034215/42801543-a0eb90a8-89a8-11e8-922d-0659b50bd103.gif)

Why?

**Comment by BLumia** [comment]
Duplicate with #4 , still thank you for reporting this.
Personally I don't have any Samsung device for testing so...... :(

Maybe this issue will be fixed in future updates, so just wait :stuck_out_tongue:
