### ISSUE TITLE
Trash empty button not exist

### ISSUE THREAD

**Issue by breadlesscode** [linuxdeepin/dde-file-manager#29]
Hi and thanks for your awsome work!

I love your filemanager but if I click on my trashbin (from dock) I have no empty trash button?

Is this a bug of this project?

Uptodate Deepin 15.3 Dektop

Trash without button: https://preview.ibb.co/iWwGWQ/Deepin_Bildschirmfoto20170411173251.png
Trash without button: https://preview.ibb.co/nEwuJ5/Deepin_Bildschirmfoto20170411172934.png

**Comment by DasJott** [comment]
Isn't this fixed?
