### ISSUE TITLE
Allow opening files by single click

### ISSUE THREAD

**Issue by thenktor** [linuxdeepin/dde-file-manager#3]
Hi,

apparently there is no setting to open files by single click instead of double click.

**Comment by manateelazycat** [comment]
@thenktor 
If allow user single click to open file like ElementryOS did, it's have bug that file will open even user just want select some file.

So we don't add this feature, anyway, thank you very for your suggestion.

Please let us know if you have any good idea. ;)

**Comment by thenktor** [comment]
@manateelazycat 
Hi, single click for opening files is available for very long time in Linux file managers. Even KDE 1 already had it as default and nowadays I don't know any common file manager, that does not at least support it (e.g. Dolphin, Thunar, PCmanFM, Nautilus). For all these file managers single click is optional.
Selecting files can be done while holding the [CTRL] key or just using a mouse selection box.

**Comment by manateelazycat** [comment]
@thenktor I have try all those file manager you said, unfortunately, I still feel that clicking open will confuse the average user.

Deepin's design principle is not to let ordinary users confused

**Comment by thenktor** [comment]
Well, I do not see any problem if default behaviour still is double click and you **have to** enable single click in the settings first.
