### ISSUE TITLE
图标模式下，单击/右键重命名，不会忽略掉扩展名

### ISSUE THREAD

**Issue by shenmo7192** [linuxdeepin/dde-file-manager#308]
dde-file-manager bug report
在列表模式下，单击/右键重命名，可以正确的忽略掉扩展名
图标模式下，单击/右键重命名，不会忽略掉扩展名

图在这
[https://shenmo.lanzoux.com/i6YLIitp0bi](url)

**Comment by deepin-CD** [comment]
感谢反馈，该问题最新版本已经解决，后续将同步到GitHub.

**Comment by deepin-CD** [comment]
由于此问题一直未得到回应，先将其暂且关闭，如有新的动态请重新打开issue。
