### ISSUE TITLE
DDE-File-Manager occupying 100% of CPU, but does not get to lock the "system".

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/dde-file-manager#309]
Hello Deepin V20 1003 Team

O DDE-File-Manager occupying 100% of CPU, but does not get to lock the "system".
When opening the service manager and searching for any file, there is a considerable delay in locating it.

![Captura de Tela_dde-desktop_20201127143358](https://user-images.githubusercontent.com/32621790/100474166-c57aa200-30be-11eb-98ce-50d46b2e782f.png)

@deepin-mozart

**Comment by FunningC0217** [comment]
Hello，I‘m dde-file-manager enginer. please show yours test case and opration setps，thanks。

**Comment by Yurii-huang** [comment]
Hello, do you have any more detailed test cases？

**Comment by serial02** [comment]
> Hello, do you have any more detailed test cases？

In these logs you will find all the errors that occur in the vast majority of DDE distros.
https://pastebin.com/u/SerialCom

If you need to generate a specific log, let me know.

@FunningC0217

**Comment by deepin-CD** [comment]
Hello，
1.Because searching in the home directory by iterator traversal and occupies a lot of CPU, we will optimize it in a subsequent release.
2.DDE-File-Manager supports quick search in data and system disks when "Auto index internal disk" is checked.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
