### ISSUE TITLE
Disable libdmr and libffmpegthumbnailer in fedora

### ISSUE THREAD

**Issue by 1dot75cm** [linuxdeepin/dde-file-manager#31]
In fedora project, some libraries is violation of the package policy. Please update the `IS_PLATFORM_FEDORA` option to fix it. https://github.com/linuxdeepin/dde-file-manager/commit/d46f81061a6c5555e8f9110aedf0aa9583e51bea

> Fedora 只允许开源而且不抵触美国法律的软件进入其官方仓库。RPM Fusion Free 是容纳使用开源许可证，但不符合 Fedora Package Guideline 要求的软件。比如 FFmpeg 和 x264，需要使用 GPL 许可证，但是因为 H.264 的专利争议而无法加入 Fedora 官方仓库。RPM Fusion Nonfree 是容纳免费，但是非开源，非商业，而且可再公开分发的软件

**Comment by zccrs** [comment]
Ok, 我们会添加可禁用参数. 请问 fedora 的 /etc/lsb-release 文件内容是什么? 也可以依照此文件内容在 fedora上默认禁用

**Comment by BLumia** [comment]
现在可通过 `CONFIG+=DISABLE_FFMPEG` 禁用 ffmpeg 了（也不再使用 `IS_PLATFORM_FEDORA` 了），相应的打包脚本应该也需要对应调整。

**Comment by 1dot75cm** [comment]
@zccrs  Fedora 上没有`/etc/lsb-release`文件，`lsb_release`命令输出如下
```
[user@localhost ~]$ lsb_release -i
Distributor ID:	Fedora
[user@localhost ~]$ lsb_release -d
Description:	Fedora release 28 (Twenty Eight)
[user@localhost ~]$ lsb_release -r
Release:	28
[user@localhost ~]$ lsb_release -c
Codename:	TwentyEight
[user@localhost ~]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight
```

@BLumia 好的，我试下

**Comment by BLumia** [comment]
没有其他问题的话这 issue 就先关掉了，有什么问题可以重新打开。
