### ISSUE TITLE
How to use MenuInterfaces for a ".so" file plugin to add new item on context menu?

### ISSUE THREAD

**Issue by joedn522** [linuxdeepin/dde-file-manager#311]
After reading https://linuxdeepin.github.io/dde-file-manager/context-menu-ext-zh.html
I know there's a way to use qt and MenuInterfaces class to create a plugin.
but after following the tutorial I insert my example so file into the 

/usr/lib/x86_64-linux-gnu/dde-file-manager/plugins/menu/

but nothing happened (I expected there's a "Sample text" on my context menu). Is there still an interface for customize plugin using MenuInterfaces?

with dde-file-manager 5.2.0.82

**Comment by deepin-CD** [comment]
The menu plugin has not been supported since dde-file-manager  5.0.4.0.
Please use the ".desktop" file in `/usr/share/deepin/dde-file-manager/oem-menuextensions` to create menu.

**Comment by deepin-CD** [comment]
> After reading https://linuxdeepin.github.io/dde-file-manager/context-menu-ext-zh.html
> I know there's a way to use qt and MenuInterfaces class to create a plugin.
> but after following the tutorial I insert my example so file into the
> 
> /usr/lib/x86_64-linux-gnu/dde-file-manager/plugins/menu/
> 
> but nothing happened (I expected there's a "Sample text" on my context menu). Is there still an interface for customize plugin using MenuInterfaces?
> 
> with dde-file-manager 5.2.0.82

The menu plugin has not been supported since dde-file-manager 5.0.4.0.
Please use the ".desktop" file in /usr/share/deepin/dde-file-manager/oem-menuextensions to create menu.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
