### ISSUE TITLE
sftp 远程相当慢

### ISSUE THREAD

**Issue by nachifur** [linuxdeepin/dde-file-manager#312]
你好，deepin的界面很好看，目前在使用ubuntudde20.04。
我测试了thunar和nautilus，速度都正常，dde-file-manager很慢。不是一个路由器下的局域网，是自己远程的局域网（openvpn）。
![image](https://user-images.githubusercontent.com/23144348/100737342-00f2d480-340f-11eb-881f-31787cec1c4c.png)
延迟正常。目前测试应该是软件dde-file-manager的问题。
![image](https://user-images.githubusercontent.com/23144348/100737550-49aa8d80-340f-11eb-81db-1d733f047c69.png)

**Comment by deepin-CD** [comment]
Access to SFPT is slow. We have optimized the network files of SMB and FTP in the latest version.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
