### ISSUE TITLE
File manager memory leak

### ISSUE THREAD

**Issue by whg517** [linuxdeepin/dde-file-manager#314]
ref: https://bbs.deepin.org/post/208397?offset=0&postId=1173796

System info: 

- `Linux kevin 5.4.70-amd64-desktop #1 SMP Wed Oct 14 15:24:23 CST 2020 x86_64 GNU/Linux`
- `20.1 Beta`
- `1005`
- CPU: Intel i5-7600K
- RAM: 32G
- dde-file-manager: `5.2.0.85`

File managers can use a lot of memory if they are opened for too long. When all Windows are closed, a process remains, which continues to occupy memory and cannot be freed. The process cannot be closed, only killed, at which point the occupied memory is freed. Generally more than 24 hours will have a significant amount of memory.

As is show in :

![img](https://bbs.deepin.org/api/v1/thread/down_image?file_path=202012210942235182_thread_WheOhNFh8MG.png)

I'll continue testing this weekend, opening the file manager on Friday and checking memory usage on Monday. Please let me know if there is any other operation that requires the system to display more details of the exception.

**Comment by deepin-CD** [comment]
Thanks!
Please attend what you do when the memory of dde-file-mamager begins to grow. It helps us to reproduce and locate the issue.

**Comment by whg517** [comment]
Hi, @deepin-CD .

Hello, I'm sorry for not recovering your message for such a long time. The main reason was that there was no time to revisit the problem. But today's surprise came on a workday.

![dde-file-manager-memory-leak](http://qiniu.iclouds.work/Fm9fVeoCXlr-xEQP0ea_Vxgg5hCW.png)

```
1  [|||||||||||||||||||||||||||||||||                                                                                    26.4%] Tasks: 301, 1901 thr, 133 kthr; 2 running
2  [||||||||||||||||||||||||||||||||                                                                                     25.8%] Load average: 1.16 1.87 2.17 
3  [|||||||||||||||||||||||||||||||||||||||||||                                                                          33.7%] Uptime: 6 days, 05:31:45
4  [|||||||||||||||||||||||||||||||||||                                                                                  28.1%]
Mem[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||29.7G/31.3G]
Swp[||||||||||||||||||||||||||||                                                                                    923M/4.00G]
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command               
15242 kevin      20   0 20.7G 17.1G 47988 S  4.2 54.8  1h46:16 /usr/bin/dde-file-manager -d
15247 kevin      20   0 20.7G 17.1G 47988 S  0.8 54.8  3:27.36 /usr/bin/dde-file-manager -d               
15243 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:21.92 /usr/bin/dde-file-manager -d               
15244 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:03.23 /usr/bin/dde-file-manager -d               
15245 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:07.70 /usr/bin/dde-file-manager -d
15246 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.01 /usr/bin/dde-file-manager -d               
15249 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:15.25 /usr/bin/dde-file-manager -d               
15250 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.00 /usr/bin/dde-file-manager -d               
15252 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.00 /usr/bin/dde-file-manager -d               
15253 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.07 /usr/bin/dde-file-manager -d               
15254 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.00 /usr/bin/dde-file-manager -d               
15314 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.01 /usr/bin/dde-file-manager -d               
15315 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.01 /usr/bin/dde-file-manager -d               
15316 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.01 /usr/bin/dde-file-manager -d               
15317 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:00.01 /usr/bin/dde-file-manager -d               
15799 kevin      20   0 20.7G 17.1G 47988 S  0.0 54.8  0:14.85 /usr/bin/dde-file-manager -d               
 7291 kevin      20   0 3423M 2125M 2069M S 71.4  6.6 52h04:09 /usr/lib/vmware/bin/vmware-vmx -
```

When i close all file-manager window, the dde-file-manager is not close. So I had to kill it.

![dde-file-manager-pid-not-close](http://qiniu.iclouds.work/FiR9I2yZkdlFSJbMRAupebc4beJe.png)

Personally, I guess this is because I opened my Downloads file and left it open for a long time, since I always opened that folder before.

In addition to the usual small download files (around 100), there is also a larger ISO folder for operating system ISO images, which is around 14GB. Yesterday, I added a new directory to store YUM warehouse compressed packages, which is about 17G for 5 files. So the Downloads directory yesterday had 32 gigabytes.

There was a memory eating situation today. Also on a weekday, I suspect this is more likely because the directory has doubled its capacity. It used to be two days on the weekend, sometimes on Monday.

I upgraded the system two weeks ago. Here is the basic information about my operating system:

- `Linux version 5.4.70-amd64-desktop (deepin@deepin-PC) (gcc version 8.3.0 (Uos 8.3.0.3-3+rebuild)) #1 SMP Wed Oct 14 15:24:23 CST 2020`
- 社区版本（1010）
- 5.4.70-amd64-desktop

If you need more detailed information, I would be happy to help. Thank you for taking time out of your busy schedule to check my reply, thank you.

**Comment by deepin-CD** [comment]
@whg517 Thanks for your help. We reproduced the issue according to your informations.
And we have located and fixed this memory leak.
![image](https://user-images.githubusercontent.com/70992023/104677323-31bf6c80-5724-11eb-8c38-d559f3a09637.png)

![image](https://user-images.githubusercontent.com/70992023/104677427-587da300-5724-11eb-8826-a408438971e3.png)

**Comment by whg517** [comment]
Thank you for your efforts and I hope my participation can make the community a better place.

I would like to ask when the repair can be updated this time?

Finally the question has been settled whether we should close it or not.

**Comment by deepin-CD** [comment]
This memory leak will be resolved at next verison of file manager.
And the patches will sync to gihub soon, then you can build the dde-file-manager and repair it early.
