### ISSUE TITLE
Deepin File Manager "Time created" and "Time accessed" missing for column in list view

### ISSUE THREAD

**Issue by din618s** [linuxdeepin/dde-file-manager#315]
**SUMMARY**
Deepin File Manager cannot add the "Time created" function for the column in the list view. There is only "Time modified".

**STEPS TO REPRODUCE**

1. Create a bootable Live USB for Deepin 20.1 with Deepin Boot Maker. 

2. Then restart the computer and boot the Live USB.

3. Install Deepin.

4. Open Deepin File Manager and activate list view.

5. Add "Time created" for column. This is not possible because this function does not exist.

**SOFTWARE/OS VERSIONS**
OS Version: `Deepin 20.1`
https://osdn.net/projects/deepin/storage/20.1_1010/

Software Version: `Deepin File Manager 5.2.0.85`

**Comment by din618s** [comment]
@deepin-CD 

Hello can you fix this problem?

Deepin File Manager in Deepin 20.1 can not add "Time created" and "Time accessed" for the column in list view because these functions are missing.

Currently only these functions are provided for the column:

- Time modified
- Size
- Type

**Comment by din618s** [comment]
@felixonmars @xmuli 
Here is a screenshot of what I mean exactly.

![Screen Capture_select-area_20210101021554](https://user-images.githubusercontent.com/76670922/103432131-fa58a800-4bda-11eb-98c7-428af764a9bd.png)

**Comment by deepin-CD** [comment]
@din618s 
Thanks for advice, this function will be considered in the long-term planning this year.

**Comment by din618s** [comment]
@deepin-CD 
Thanks for the answer. Here are some more reports. Please fix all of them.

https://github.com/linuxdeepin/dde-file-manager/issues/318
https://github.com/linuxdeepin/dde-file-manager/issues/319
https://github.com/linuxdeepin/dde-file-manager/issues/320
https://github.com/linuxdeepin/dde-file-manager/issues/321

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.

**Comment by din618s** [comment]
> This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.

This is not fixed Deepin File Manager 5.2.0.85 (latest version).
