### ISSUE TITLE
Does not display the original timestamp "Time created" on FAT, FAT32, exFAT and NTFS disks

### ISSUE THREAD

**Issue by din618s** [linuxdeepin/dde-file-manager#318]
**SUMMARY**
Deepin File Manager shows the same time for "Time created" as "Time modified" for files and folders on external disks with FAT, FAT32, exFAT and NTFS as file system.

**STEPS TO REPRODUCE**

1. Open Deepin File Manager on the computer.

2. Connect external disks (e.g. USB flash drive). These disks have these file systems: FAT, FAT32, exFAT and NTFS

3. View the folders and files on these disks via right click "Property". You see under "Time created" the same time as for "Time modified". This is wrong.

**SOFTWARE/OS VERSIONS**
OS Version: `Deepin 20.1`
Software Version: `Deepin File Manager 5.2.0.85`

**Additional Information**

When I test it under Windows 10 there are not these problems. Windows File Explorer shows the correct time for "Time created" for folders and files.

It seems that Deepin File Manager does not read the correct values for these file systems (FAT, FAT32, exFAT and NTFS).

**Comment by itsXuSt** [comment]
> **SUMMARY**
> Deepin File Manager shows the same time for "Time created" as "Time modified" for files and folders on external disks with FAT, FAT32, exFAT and NTFS as file system.
> 
> **STEPS TO REPRODUCE**
> 
> 1. Open Deepin File Manager on the computer.
> 2. Connect external disks (e.g. USB flash drive). These disks have these file systems: FAT, FAT32, exFAT and NTFS
> 3. View the folders and files on these disks via right click "Property". You see under "Time created" the same time as for "Time modified". This is wrong.
> 
> **SOFTWARE/OS VERSIONS**
> OS Version: `Deepin 20.1`
> Software Version: `Deepin File Manager 5.2.0.85`
> 
> **Additional Information**
> 
> When I test it under Windows 10 there are not these problems. Windows File Explorer shows the correct time for "Time created" for folders and files.
> 
> It seems that Deepin File Manager does not read the correct values for these file systems (FAT, FAT32, exFAT and NTFS).

Hi @din618s 

Sorry too late to answer you.

I tested your issue, and it do reproduce on my pc.
![image](https://user-images.githubusercontent.com/50353838/104989623-c4a52300-5a12-11eb-9550-d20c9d86f0c2.png)
![image](https://user-images.githubusercontent.com/50353838/104989781-1352bd00-5a13-11eb-9c3a-bea4886b3a1d.png)

Execute the command 'stat' on those files or dirs, it shows the same created timestamp like the property dialog of dfm did, so this issue is not something wrong with dfm, dfm shows the same with the cmd execution, but something wrong with the VFS, the info is provided by the VFS layer, and these filesystem you mentioned are original filesystem on Windows, Linux implemented the fs-driver. 

So it is an up-stream issue (maybe Linux kernel), not dfm's.

Hope this answer can help you.

**Comment by din618s** [comment]
@itsXuSt 

**Tested with FAT32 USB drive.** Please see my `stat` command, it shows that created time = Birth is not displayed.
> deepin@deepin:~$ stat -f '/media/deepin/FEDORA-KDE-/66.txt'
  File: "/media/deepin/FEDORA-KDE-/66.txt"
    ID: 81100000000 Namelen: 1530    Type: msdos
Block size: 16384      Fundamental block size: 16384
Blocks: Total: 1946846    Free: 1823098    Available: 1823098
Inodes: Total: 0          Free: 0


> deepin@deepin:~$ stat '/media/deepin/FEDORA-KDE-/66.txt'
  File: /media/deepin/FEDORA-KDE-/66.txt
  Size: 0               Blocks: 0          IO Block: 16384  regular empty file
Device: 811h/2065d      Inode: 173         Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  deepin)   Gid: ( 1000/  deepin)
Access: 2021-01-20 00:00:00.000000000 +0100
Modify: 2021-01-20 19:01:08.000000000 +0100
Change: 2021-01-20 19:01:08.510000000 +0100
 Birth: -

---

I also found out why Deepin 20.1 does not display created time = Birth in general with `stat`, because it uses coreutils 8.30.3 (outdated version).

> deepin@deepin:~$ stat -f '/home/deepin/Documents/zurttre.txt'
  File: "/home/deepin/Documents/zurttre.txt"
    ID: 865605fb29301a77 Namelen: 255     Type: ext2/ext3
Block size: 4096       Fundamental block size: 4096
Blocks: Total: 19499183   Free: 19386448   Available: 18385181
Inodes: Total: 4988928    Free: 4987190

> deepin@deepin:~$ stat '/home/deepin/Documents/zurttre.txt'
  File: /home/deepin/Documents/zurttre.txt
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 807h/2055d      Inode: 1835411     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  deepin)   Gid: ( 1000/  deepin)
Access: 2021-01-20 19:33:29.000000000 +0100
Modify: 2021-01-20 19:33:07.000000000 +0100
Change: 2021-01-20 19:35:28.016256000 +0100
 Birth: -

Since coreutils 8.31 and later you can use `stat` to display created time = birth time if the filesystem has stored it. Please update Deepin developers.
https://lists.gnu.org/archive/html/coreutils/2019-03/msg00042.html

**Comment by itsXuSt** [comment]
thanks @din618s , your suggestion will be considered.
and later i'll try it on my pc.

**Comment by deepin-CD** [comment]
> https://lists.gnu.org/archive/html/coreutils/2019-03/msg00042.html

yes, i have viewd the improvements. we will make an internal verification, and if it is really useful, we will update it on our later version.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
