### ISSUE TITLE
Add change time (ctime) for files and folders

### ISSUE THREAD

**Issue by din618s** [linuxdeepin/dde-file-manager#319]
**SUMMARY**
Deepin File Manager does not display change time (ctime) for folders and files.

**STEPS TO REPRODUCE**

1. Open Deepin File Manager on the computer.

2. View local folders and files via right click "Property".

3. Change time (ctime) is missing

**SOFTWARE/OS VERSIONS**
OS Version: `Deepin 20.1`
Software Version: `Deepin File Manager 5.2.0.85`

**Additional Information**

Change time (ctime) can be displayed with `stat` command

More information about file system timestamps
https://wiki.sleuthkit.org/index.php?title=Mactime_output

**Comment by deepin-CD** [comment]
Excuse，environment：
deepin 20.1 version 
dde-file-manager 5.2.0.85

click "Properties" show a widget，You can find 
Basic info>  
Time created：time from file create
Time accessed：time from access to file 
Time modified：time from file changed

Maybe tell me what file system (network / Udisk) you operate on.

**Comment by din618s** [comment]
> Excuse，environment：
> deepin 20.1 version
> dde-file-manager 5.2.0.85
> 
> click "Properties" show a widget，You can find
> Basic info>
> Time created：time from file create
> Time accessed：time from access to file
> Time modified：time from file changed

Note: Birth = created time = Time created is not shown in Deepin 20.1 because you are using coreutils 8.30.3 and that is outdated. You need to add coreutils 8.31 or later so that created time is also displayed in Deepin with `stat` command.
https://lists.gnu.org/archive/html/coreutils/2019-03/msg00042.html

> deepin@deepin:~$ stat -f '/home/deepin/Documents/zurttre.txt'
File: "/home/deepin/Documents/zurttre.txt"
ID: 865605fb29301a77 Namelen: 255 Type: ext2/ext3
Block size: 4096 Fundamental block size: 4096
Blocks: Total: 19499183 Free: 19386448 Available: 18385181
Inodes: Total: 4988928 Free: 4987190

> deepin@deepin:~$ stat '/home/deepin/Documents/zurttre.txt'
File: /home/deepin/Documents/zurttre.txt
Size: 0 Blocks: 0 IO Block: 4096 regular empty file
Device: 807h/2055d Inode: 1835411 Links: 1
Access: (0644/-rw-r--r--) Uid: ( 1000/ deepin) Gid: ( 1000/ deepin)
Access: 2021-01-20 19:33:29.000000000 +0100
Modify: 2021-01-20 19:33:07.000000000 +0100
Change: 2021-01-20 19:35:28.016256000 +0100
Birth: -


> Maybe tell me what file system (network / Udisk) you operate on.

I just want all the timestamps to be displayed in Deepin File Manager, like a `stat` command. Deepin File Manger 5.2.0.85 (last version) does not show all timestamps like `stat`. It is missing **Change** = change time (ctime).

I am testing ext4 and Btrfs as filesystem for internal and external disks. But, there are still a lot of problems on Deepin (Linux) and this is also one of the reasons why I still use Windows 10.

My most used filesystems are NTFS, FAT32 and exFAT, but I would like to switch to Deepin, but I can't because of too many problems. I want to keep all my timestamps for folders and files also for the "Copy" function.

**Comment by deepin-CD** [comment]
Thank you for your feedback. Related functions will be supported in the subsequent development

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
