### ISSUE TITLE
Admin Option Disable High Dpi

### ISSUE THREAD

**Issue by ashvinnihalani** [linuxdeepin/dde-file-manager#32]
When I open a folder in root with the "open folder in root" it scales down and becomes unreadable.

**Comment by BLumia** [comment]
It's a known issue, thank you for reporting this btw.

**Comment by BLumia** [comment]
Should be fixed in [#130278c](https://github.com/linuxdeepin/dde-file-manager/commit/130278cdf1c1f1bd80876fcc0c4534c7ae39b856) ;)
