### ISSUE TITLE
Add: Set timestamp for folders and files to current time after copying

### ISSUE THREAD

**Issue by din618s** [linuxdeepin/dde-file-manager#320]
**SUMMARY**
There are no additional options in Deepin File Manager to decide which timestamp to keep or set at the current time for copying local folders and files.

**STEPS TO REPRODUCE**

1. Open Deepin File Manager on the computer.

2. Copy local folders and files to external disks (ext4 or Btrfs filesystem). In this case the user wants to set the copied folders and files for all timestamps to current time.

3. This is not possible because these options do not exist

**SOFTWARE/OS VERSIONS**
OS Version: `Deepin 20.1`
Software Version: `Deepin File Manager 5.2.0.85`

**Additional Information**

_Describe the solution you'd like_

Options should be added to the settings in Deepin File Manager that allow users to decide whether to set the timestamp to the current time when copying folders and files.

This is how it should look like.

Set timestamp to current time after copying

Folder:
Creation time (on/off)
Access time (on/off)
Modified time (on/off)
Change time (on/off)

File:
Creation time (on/off)
Access time (on/off)
Modified time (on/off)
Change time (on/off)

**Comment by din618s** [comment]
**Additional Information 2**

This must also be supported by Deepin Compressor, because there are archives that store timestamps e.g ZIP
https://github.com/linuxdeepin/deepin-compressor

**Comment by deepin-CD** [comment]
Thank you for your attention and support for deepin. For this problem, it should not be suitable for user mode file management software. If you need to support marking to prevent the current memo, you can try to use the marking function of file manager.

**Comment by deepin-CD** [comment]
Thank you for your attention and support for deepin. This problem has been fixed in the latest version of file manager. The attribute column contains three items: creation time / access time / change time

**Comment by din618s** [comment]
> Thank you for your attention and support for deepin. For this problem, it should not be suitable for user mode file management software. 

This is illogical on Windows 10 works with other file manger software (GUI) and robocopy.exe

The users on Windows 10 can decide it themselves and this behavior must be changed in Deepin. This is also one of the reasons why I prefer Windows 10 than Deepin. Windows 10 has much more possibilities for me as a user than Deepin (Linux).

> If you need to support marking to prevent the current memo, you can try to use the marking function of file manager.

What exactly do you mean by marking function? You mean "Cut" function? No I don't want to use a "Cut" function because a copy is made for the file or folder, but I want to use the "copy" function.

**Comment by din618s** [comment]
> Thank you for your attention and support for deepin. This problem has been fixed in the latest version of file manager. The attribute column contains three items: creation time / access time / change time

This is not correct. Deepin File Manager 5.2.0.85 (latest version).

Supports these timestamps:

creation time (`crtime`) = birth time (`btime`) / access time (`atime`) / modified time (`mtime`)

change time (`ctime`) is not supported.

**Comment by deepin-CD** [comment]
Thank you for your feedback. Related functions will be supported in the subsequent development

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
