### ISSUE TITLE
Default created file/folder at a Deepin installation must set original creation time

### ISSUE THREAD

**Issue by din618s** [linuxdeepin/dde-file-manager#321]
**SUMMARY**
When users install Deepin on the computer for the first time and view the default folders and files created by Deepin system after installation.

Deepin File Manager displays illogical timestamps for creation time (Time created).

An example 
Time created: 2021/01/01 01:01:01
Time modified: 2021/01/01 01:01:01

In this case "Time created" has taken the same time as "Time modified". That is, the installation time was taken and not the original creation time.

Windows 10 and Windows 8 do not do it. For example, if users reinstall Windows 8 on their computer today in 2021. Then it will show the original creation time for the default created folders and files from the system and not set to current time.

An example 
Time created: 2013/01/01 01:01:01
Time modified: 2021/01/01 01:01:01

**SOFTWARE/OS VERSIONS**
OS Version: `Deepin 20.1`
https://osdn.net/projects/deepin/storage/20.1_1010/

Software Version: `Deepin File Manager 5.2.0.85`

**Additional Information**
The problem should be fixed in future Deepin versions, preferably in the next major Deepin version this year.

**Comment by din618s** [comment]
**Additional information 2 (very important!):**
The files (example a .txt file) and folders when user first create on Deepin must have a empty modified time (mtime).

This logical behavior must be applied.
Deepin File Manager must display a empty modified time (`mtime`). An empty modified time (`mtime`) in Deepin File Manager should work because I think the ext4 filesystem supports it.

An example of a future Deepin version that has completely fixed the problem. A file and folder created at 2021/01/01 00:00:00

`btime` (birth time = created time):
2021/01/01 00:00:00

`atime` (access time):
2021/01/01 00:00:00

`mtime` (modified time):
— (empty)

`ctime` (change time):
— (empty)

Note:
If users are using filesystems that cannot display an empty modified time (`mtime`). Then birth time (`btime`) must be taken. This would suggest that the contents of the file and folder were modified, which is wrong. But so it is on filesystems that do not support it, mostly very old filesystems. The current filesystems, like ext4, Btrfs, ZFS, NTFS, exFAT should support it.

**Comment by deepin-CD** [comment]
Thank you for your feedback. Related functions will be supported in the subsequent development

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
