### ISSUE TITLE
sftp connection is failed

### ISSUE THREAD

**Issue by nachifur** [linuxdeepin/dde-file-manager#324]
version:
![image](https://user-images.githubusercontent.com/23144348/105574361-06c9be00-5d9f-11eb-9b4e-a7cbd1633572.png)

![image](https://user-images.githubusercontent.com/23144348/105574308-b2bed980-5d9e-11eb-8af0-e3b8bcc9b127.png)
problem:
dde-file-manager sftp connection is failed. Two computer is ubuntudde 20.10.
![image](https://user-images.githubusercontent.com/23144348/105574379-1fd26f00-5d9f-11eb-9809-d65889b5b67c.png)
![image](https://user-images.githubusercontent.com/23144348/105574395-3ed10100-5d9f-11eb-9864-897add6ccb7d.png)
![image](https://user-images.githubusercontent.com/23144348/105574318-bf433200-5d9e-11eb-885a-80fe3eab5d68.png)
thunar and nautilus is ok!
![image](https://user-images.githubusercontent.com/23144348/105574406-53ad9480-5d9f-11eb-9cbe-2af6e0556106.png)

**Comment by ghost** [comment]
same here, 5.2.0.87

**Comment by deepin-CD** [comment]
to connect ssh service from show image, why next image is connection sftp service？

**Comment by deepin-CD** [comment]
failed connection test case from sftp service connection, and the view can show all dirs, is right?

**Comment by nachifur** [comment]
> failed connection test case from sftp service connection, and the view can show all dirs, is right?

yes! it shows all dirs, but don't connect sftp.

**Comment by deepin-CD** [comment]
Thank you for your feedback. We have recorded your problem and will update it in the following version.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
