### ISSUE TITLE
Make automatic mounting of available network shares as easy as on Windows 10

### ISSUE THREAD

**Issue by Atalanttore** [linuxdeepin/dde-file-manager#325]
It would be very useful if the automatic mounting of available SMB network shares in Deepin would be as easy as on Windows 10.

The Windows Explorer automatically queries servers in the local network for all available shares. Once you have opened and pinned a network share in Windows Explorer, it is automatically mounted if it is available on the current local network. If not, a decent notification will appear informing you that not all network shares could be mounted.

On Linux, you have several options for automatically mounting shares available on the current local network. First, you have to install `cifs-utils`. Then you have to
- install `autofs` and create several cryptic configuration files or
- create a cryptic `systemd` unit file or
- use a dedicated tool from your desktop environment for setup, if there is such a tool or
- do something else.

It is important that a path to access a network share does not start with `smb://` because not all programs on Linux support this protocol (flawlessly).

Up to now, all options on Linux require more time and frustration tolerance than on Windows.

Maybe Deepin could put an end to this unsightly Linux tradition and match the comfort of Windows 10.

**Comment by Clauszy** [comment]
@Atalanttore 
The "automatically mounting shares" you metioned above is a samba browse service. In fact, Deepin has built-in the samba service, so it is available to interact with windows or other Linux systems which provide samba service in LAN.
Before using the service, you sould first check whether the smbd and nmbd service work corectly, and then check the workgroups in dde-file-manager. 
By the way, if all machines in your local network are Linux systems , it is necessary to make one machine to be the "local master" or "domain master".

**Comment by deepin-CD** [comment]
Deepin provide samba service include smbd and nmbd, and also the samba client utilities include browse and peer to peer connection by dde-file-manager.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
