### ISSUE TITLE
Better translation for dropdown menu

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/dde-file-manager#327]
Meaning will remain basically the same, however in a simpler and more elegant manner. 
 
![image](https://user-images.githubusercontent.com/39202451/107685274-181e3000-6ca4-11eb-88eb-f650ebf290cf.png)

**Comment by Clauszy** [comment]
@vesterlay Thanks for your suggestion.

**Comment by deepin-CD** [comment]
Thank you for your feedback. 
We have recorded your problem and will update it in the following version.

**Comment by raspin0** [comment]
> Thank you for your feedback. 
> We have recorded your problem and will update it in the following version.

I've made a mistake! The administrator should be lower-case. "Open as administrator" not "Open as Administrator".

Sorry for the inconvenience

**Comment by deepin-CD** [comment]
Ok,"Open as administrator" is good.

**Comment by raspin0** [comment]
Marvelous, changes have been merged. Closing issue
