### ISSUE TITLE
无法设置壁纸，闪退。

### ISSUE THREAD

**Issue by forliuyifei** [linuxdeepin/dde-file-manager#328]
https://user-images.githubusercontent.com/53306807/107178986-500d4500-6a10-11eb-80f9-8a3cbff038dd.mp4

![图片](https://user-images.githubusercontent.com/53306807/107179043-7b902f80-6a10-11eb-8258-da3dc9a4ab1d.png)

**Comment by deepin-CD** [comment]
@forliuyifei Please provide more information including coredump,log of dde-desktop,version of window manager .etc.
And how to reproduce the issue.

**Comment by forliuyifei** [comment]
> @forliuyifei Please provide more information including coredump,log of dde-desktop,version of window manager .etc.
> And how to reproduce the issue.

Sorry I have returned to Deepin OS, so couldn't provide more information.

I faced this bug using Arch Linux + DDE, have no idea if there's anything missed.

**Comment by deepin-CD** [comment]
Thanks for the information, we will temporary close this issue, if you face this issue again, please provide more information for us, we will educate this issue again.
