### ISSUE TITLE
DISABLE_SCREENSAVER option cannot be turned off

### ISSUE THREAD

**Issue by ppphp** [linuxdeepin/dde-file-manager#329]
`m_waitControl` appears in `dde-wallpaper-chooser/frame.cpp`. It was controlled by `DISABLE_SCREENSAVER` option in the header file. If `DISABLE_SCREENSAVER` is on, compiling fails.

**Comment by Clauszy** [comment]
@ppphp Thank you for your feedback.
We have recorded the issue and will fix it soon.

**Comment by deepin-CD** [comment]
Thanks.
This issue is being worked on.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
