### ISSUE TITLE
Not able to compile 🤷😔

### ISSUE THREAD

**Issue by amustaque97** [linuxdeepin/dde-file-manager#33]
I'm trying to compile the dde-file-manager locally on my ubuntu 18.04 but it is showing some unknown module error. All the dependencies have been installed but still no progress.
![deepinscreenshot_desktop_20180821204349](https://user-images.githubusercontent.com/21127788/44411587-7ca11e00-a584-11e8-8392-a309c94b3693.png)

**Comment by BLumia** [comment]
You are probably missing [libkf5codecs5](https://packages.ubuntu.com/xenial/kde/libkf5codecs5) package (and the related -dev package).

Take a look at `[package_source_path]/debian/control` file and it will show you all build depends you'll need.

**Comment by BLumia** [comment]
We've updated the README.md 's build-depends part, hope that helps.

You can also disable some components if you like, use `qmake CONFIG += <config name here>` to toggle some build flags. These fiags are available now (v1.8.1):

 - `DISABLE_FFMPEG` : disable ffmpeg,
 - `DISABLE_ANYTHING` : disable deepin-anything module, deepin-anything is a kernel module for vfs_change monitoring to provide fast file indexing feature, if you are not using deepin-anything module, you can disable it.
 - `BUILD_MINIMUM` Minimum build. Please notice that a minimum build is still with deepin-anything module support if you are not use it with `DISABLE_ANYTHING` at the same time.

Dig into the .pro files if you are interested about other flags which are not listed here.

Feel free to reopen this issue if you got any further questions about building the file manager :)
