### ISSUE TITLE
部分软件在选择文件时会闪退

### ISSUE THREAD

**Issue by deltacatxx** [linuxdeepin/dde-file-manager#330]
如题，我这里发现一部分软件在要打开文管选择文件时会软件发生闪退问题。

目前已知软件：浏览器、HMCL我的世界启动器。

问题描述：在一些需要打开文管选择文件的情况下，无法选择文件并且软件会发生闪退。

例如：我在论坛发一个帖子，需要上传一个图片，但我点击插入图片—上传—浏览图像时，浏览器就会奔溃闪退。

用终端打开HMCL，闪退时会在终端输出以下错误信息：

(java:16208): Gtk-WARNING **: 15:13:38.021: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(java:16208): GLib-GIO-ERROR **: 15:13:38.258: Settings schema 'org.gtk.Settings.FileChooser' is not installed
追踪与中断点陷阱

**Comment by Clauszy** [comment]
@deltacatxx 感谢反馈。
请提供硬件平台，dde-file-manager的版本号，以及准确地复现环境和步骤。

**Comment by deltacatxx** [comment]
dde-file-manager版本号：5.2.0.87
[设备信息20210224_124438.txt](https://github.com/linuxdeepin/dde-file-manager/files/6033423/20210224_124438.txt)
应该是最近才出现的bug，之前没有遇到过。

**Comment by deepin-CD** [comment]
感谢反馈。
正在分析该问题。

**Comment by deepin-CD** [comment]
@deltacatxx 请提供一下更加详细的信息。
使用的浏览器版本，检查文件夹中是否存在比较特殊文件，如果可以请上传下复现过程的视频

**Comment by deltacatxx** [comment]
可能有点模糊……
视频内容大概就是：凡是要打开文管选择文件或者路径之类的操作都会使当前软件奔溃。
基本都是第三方应用，深度自带的应用没有这个问题
[截图录屏_选择区域_20210226133633.zip](https://github.com/linuxdeepin/dde-file-manager/files/6047578/_._20210226133633.zip)

**Comment by deepin-CD** [comment]
@deltacatxx 我们安装Deepin 20.1的镜像后测试，没有复现到该问题。

如果可以，麻烦你重新安装一个Deepin 20.1，检查是否有该问题。
然后对比一下是在做了什么操作或安装了什么应用后会出现问题。

我们本地需要按照你提供的复现路径进行复现，然后分析，感谢。

**Comment by deltacatxx** [comment]
重装后发现没有这个问题了……
我也记不起来当时干了什么导致的，抱歉

**Comment by deepin-CD** [comment]
@deltacatxx 如果您重新遇到类似问题，您可以再在这里反馈详细的信息，我们本地也会继续观察是否会有类似的问题。谢谢您的反馈。
