### ISSUE TITLE
文件拖动效果改进建议

### ISSUE THREAD

**Issue by a137933** [linuxdeepin/dde-file-manager#331]
文件预先效果改进建议
https://bbs.chinauos.com/zh/post/5401
文管侧边栏和书签优化建议
https://bbs.chinauos.com/zh/post/3305
文管多标签时，当前标签不够明显
https://bbs.chinauos.com/zh/post/3304

**Comment by deepin-CD** [comment]
We will seriously consider your suggestion. Thank you for your suggestion.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.

**Comment by a137933** [comment]
> 由于未收到任何回应，此问题将暂时关闭。如果有任何新更新，请重新打开该问题。

？？

**Comment by deepin-CD** [comment]
已收到你的建议，并在评估中。
