### ISSUE TITLE
文件属性窗口UI有问题，无法点击

### ISSUE THREAD

**Issue by a137933** [linuxdeepin/dde-file-manager#332]
https://bbs.chinauos.com/zh/post/3597

**Comment by deepin-CD** [comment]
感谢反馈，该问题正在处理中并将在下个版本修复。

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.

**Comment by a137933** [comment]
> 由于未收到任何回应，此问题将暂时关闭。如果有任何新更新，请重新打开该问题。

还需要啥回应？？

**Comment by deepin-CD** [comment]
该问题已处理。
