### ISSUE TITLE
目前是否有支持用户添加自定义文件属性的接口

### ISSUE THREAD

**Issue by yuanxingdewoniu** [linuxdeepin/dde-file-manager#337]
想确认一下目前有没有开放添加自定义文件属性的接口，目前看代码有dde-file-manager-plugins插件模块，但是不清楚能不能添加自定义的文件属性，如果有，怎样使用？ 

nautial 提供这样的一个接口nautilus_file_info_add_emblem ()，用户使用用这个接口，编写的so库，放到系统的指定路径，便可以给文件增加自定义的属性，
nautilus_file_info_add_emblem ()
void nautilus_file_info_add_emblem (NautilusFileInfo *file,
                               const char *emblem_name);

**Comment by deepin-CD** [comment]
@yuanxingdewoniu PropertyDialogExpandInfoInterface 能否满足你的需求呢？

**Comment by deepin-CD** [comment]
由于此问题一直未得到回应，先将其暂且关闭，如有新的动态请重新打开issue。
