### ISSUE TITLE
Add documentation on how you can add a menu entry.

### ISSUE THREAD

**Issue by TheRealSyler** [linuxdeepin/dde-file-manager#338]
I found no english documentation on how to add a menu entry, so i figured it out by google translating and a little bit of source code reading,  i saw that there is a edit button on the [Docs Website](https://wiki.deepin.org/wiki/Deepin_File_Manager) so i created an account only to find out that i cant edit the docs, anyways here is the addition that i wanted to make, its probably better this way since i'm unsure if everything that i wrote is correct. 

Im unsure about are why is the File manager process called `dde-file-manage`, is it a bug?

also is there already a way to make plugins for the file manager?, i just want to know because i might want to create one in the future. 

and another thing is there a way to determine where the item gets added?, like for example can i add an item the is always the first item in the menu?

---
## Add New Menu Entry

You can add a new menu entry by adding a `.desktop` file in the `/usr/share/deepin/dde-file-manager/oem-menuextensions` directory, here is a simple example, create a new file named `edit.desktop` (Requires root permissions):
```ini
[Desktop Entry]
Type=Application
Exec=/usr/bin/deepin-editor %U
Name=Edit with your favorite editor
X-DFM-MenuTypes=SingleFile
```
Then close all File Manager windows and kill the process by using `sudo pkill dde-file-manage` (its not a typo for some reason there is no `r` at the end), now you can reopen the File Manager and when you right click on a file you should see a new menu entry named `Edit with your favorite editor`.

### Sub Menu Example 
``` ini
[Desktop Entry]
Type=Application
Icon=utilities-terminal
Name=Sub Menu Example
Actions=TestAction;
X-DFM-MenuTypes=SingleFile;SingleDir;MultiFileDirs;EmptyArea

[Desktop Action TestAction]
Name=Sub Menu Item
Exec=/usr/bin/dde-calendar
```
### Additional Keys
Fore more info on what keys you can use in  `.desktop` files you can take a look at the [spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/).

| Name | Description | Values|
| - | - |-|
| `X-DFM-MenuTypes` | Determines when in which context the entry gets added.| `Singlefile` ,  `Singledir` , `MultiFiledirs`, `Emptyarea` |
| `X-DFM-ExcludeMimeTypes` | Hides the entry if it matches the mimeType.|Any MimeType, can be separated with a `;`|
| `X-DFM-NotShowIn` | Hide the entry on the Desktop or in the File Manager.  |` FileManager`, `Desktop` |
| `X-DFM-SupportSchemes` | Shows the item in the directory scheme. |` File`, `Trash`,` Recent`, `Bookmark`|
| `X-DFM-SupportSuffix` | Shows the item if it matches a given Suffix |RegExp|

**Comment by deepin-CD** [comment]
The detail infomation for menu entry lists in 
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions

And now the position of additional menu is not spported to configure.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
