### ISSUE TITLE
installing from source code issue

### ISSUE THREAD

**Issue by akramAbou** [linuxdeepin/dde-file-manager#339]
I accidentally deleted the file manager, and when I tried installing it back from the source code, I followed all the steps but when I get to build the project ($ qmake ..), I get this error 
![image](https://user-images.githubusercontent.com/80842321/111507733-42538980-874b-11eb-819f-3a0a3093bd16.png)

I really liked this file manager so am hoping I can get it back.

**Comment by deepin-CD** [comment]
Try this command  `qmake ../filemanager.pro`

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
