### ISSUE TITLE
Feature suggestion: Add tags to the partition by default

### ISSUE THREAD

**Issue by pgy866** [linuxdeepin/dde-file-manager#34]
Feature suggestion: Add tags to the partition by default

**Comment by BLumia** [comment]
Hi and please **don't delete the issue template** for feature request, you should edit the issue template with your suggestion just like filling in a form.

Please also make sure if your suggest is related to the file manager. If you are not sure about that, you should probably fire a issue in [Developer Center](https://github.com/linuxdeepin/developer-center) or the [Offical User Forum](https://bbs.deepin.org).

Feel free to reopen this issue if you update your feature request context include these sections mentioned in the feature request issue template.
