### ISSUE TITLE
BUG - Bugged address bar while looking for a location 

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/dde-file-manager#341]
**It does not reproduce in File Manager itself.** You have to prompt some sort of quick select (like ctrl+s on the website to make this bug appear).

https://user-images.githubusercontent.com/39202451/112729480-9a994100-8f2c-11eb-9d48-ae949aab60ee.mp4

**Comment by deepin-CD** [comment]
Thank you for your feedback. 
We have fixed this bug and will update it in the following version.

**Comment by raspin0** [comment]
Wow, thank you for your work!
