### ISSUE TITLE
 [Feature Request] Change alt+number to ctrl+number to cycle between tabs

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/dde-file-manager#343]
Using ctrl is more accessible and convenient from my experience. Adding a switch to the settings would also be a good idea I guess.

**Comment by deepin-CD** [comment]
Thank you for your suggestion.
And could you give us more detail about the feature?

**Comment by raspin0** [comment]
Put your hands on the keyboard like you usually do. Open file manager and create a couple of tabs(CTRL+T), now try to juggle between them with alt+number(1,2,3,etc). Don't you have a sensation like you had to stretch your hand to access alt? You basically have to take your finger off the space to juggle. 

With CTRL on the other hand you can do it without ruining your hands positioning with top right corner of your palm(area under your small finger). It's way more convenient. It's the exact same issue Firefox has, that's why this addon was created https://addons.mozilla.org/en-US/firefox/addon/ctrl-number-to-switch-tabs/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by deepin-CD** [comment]
Thanks, we will seriously consider your suggestion.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed. Please reopen the issue if there're any new updates.
