### ISSUE TITLE
[Feature Request] Apply branding to ~./Games folder and add automatically to side panel

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/dde-file-manager#344]
To make deepin even more coherent when a ~./Games folder is detected, apply Game folder icon and add it automatically to the sidebar.

**Comment by deepin-CD** [comment]
The bookmark is useful.

You could use ‘Add to bookmark’ in contextmenu to add the Games folder to sidebar.

**Comment by raspin0** [comment]
Yeah, but in this case there is no specific folder icon on it. I feel like marking ~./Games folder as a "native" that would appear alongside Desktop, Videos, Music.. folders as you install your first game would be awesome. Please close if you dislike this idea.

**Comment by deepin-CD** [comment]
Thanks for your suggestion.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed. Please reopen the issue if there're any new updates.
