### ISSUE TITLE
BUG? - File extension is highlighted while renaming a file in icon view

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/dde-file-manager#345]
I don't know if it has been made on purpose, but right now when you rename a file in the **icon view** it highlights entire name along with file extension. I don't find it very convenient.

**Comment by itsXuSt** [comment]
Could you please provide your version of dde-file-manager to help us make sure if this issue was already solved?

**Comment by raspin0** [comment]
![image](https://user-images.githubusercontent.com/39202451/112791997-e8b06080-9062-11eb-9ecd-75a473baebbe.png)

**Comment by deepin-CD** [comment]
Thanks for your feedback.
We have fixed this bug and will update it in the following version.

**Comment by raspin0** [comment]
The issue has been resolved
