### ISSUE TITLE
[Feature Request] Set plain text to be always first option in dropdown menu

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/dde-file-manager#346]
It's rather a small detail, but empty text being the most versatile and most used file should always be placed first in the drop down menu.

**Comment by deepin-CD** [comment]
We will seriously consider your suggestion. Thank you for your suggestion.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed. Please reopen the issue if there're any new updates.
