### ISSUE TITLE
Why those characters are blocked? 

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/dde-file-manager#347]
I've came across an issue with having multiple files from windows that contain block brackets `[` which are removed on rename by the file manager. Why? 

Characters not allowed for filenames:
Windows NTFS - `/\:*"?<>|`
UNIX EXT4 BTRFS XFS - All except `/` and `NUL ('\0')`

There is no need to block `' [ ] + = ; ,`

sources: 
Windows:
https://en.wikipedia.org/wiki/NTFS
Mac:
https://en.wikipedia.org/wiki/Apple_File_System
Linux:
https://en.wikipedia.org/wiki/XFS
https://en.wikipedia.org/wiki/Btrfs
https://en.wikipedia.org/wiki/Ext4

**Comment by deepin-CD** [comment]
Thanks for your feedback.
We have recorded this issue and will consider your suggestion.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed. Please reopen the issue if there're any new updates.
