### ISSUE TITLE
Shows incorrect total space and used space.

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#35]
dde-file-manager shows incorrect amount of total space and used space of a disk.

**To Reproduce**
Just mount a disk with less than 1 GB space and you will see it.

I expected that dde-file-manager would display the correct total space and used space of a disk.

Here is a picture of it.

![deepinscreenshot_dde-file-manager_20180825114919](https://user-images.githubusercontent.com/33563064/44615534-fb84a800-a85d-11e8-9d87-b1c2bdad4cb5.png)

Distro is Linux Deepin 15.7
Version of dde-file-manager is 1.8.1

**Comment by BLumia** [comment]
What's the size of that partition exactly?

``` shell
$ df -BM
```

**Comment by SiamSami** [comment]
The size of that partition is 200MB.

**Comment by BLumia** [comment]
This should be fixed now, please wait for next release or build it by yourself if you wish to use it now :)
