### ISSUE TITLE
Deepin File Manager won’t open 

### ISSUE THREAD

**Issue by christianbearslyclark** [linuxdeepin/dde-file-manager#350]
I  have  Ubuntu DDE 20.10

I have done some upgrades. 

Now the Deepin file manager won’t open: 

how to fix this ?

thanks.

**Comment by christianbearslyclark** [comment]
... never mind .....the Deepin File Manager seems to be working now LOL  ...so weird  tho.

**Comment by deepin-CD** [comment]
Please contact us and submit the log of Deepin File Manager if it reproduces again.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed. Please reopen the issue if there're any new updates.
