### ISSUE TITLE
删除右键压缩菜单

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-file-manager#352]
右键压缩菜单不需要，怎么删除？
![alt](https://ae01.alicdn.com/kf/Uf0cad573ce494e81af38ce26d633b063f.jpg)

**Comment by deepin-CD** [comment]
在`/usr/share/applications/context-menus`目录下找到对应的菜单配置文件，注释掉不需要的菜单项既可。

**Comment by sonichy** [comment]
```
#Actions=Zero:One:Two
Actions=Zero
```

**Comment by linuxlin365** [comment]
@deepin-CD 如何屏蔽左侧的菜单，列如保险箱、网络邻居？
