### ISSUE TITLE
Changing icon of a specific file

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#36]
Deepin file manager doesn't allow us to change icon of a specific file. For example, if we create a shortcut file, then we can't change the icon of it using deepin file manager like we can in Windows.

I want to be able to change icon of a file or some files specifically.

**Comment by BLumia** [comment]
Please **use the issue template** for feature request.

For your requirement, you need a `.desktop` file for your executable file so you can customize it. A symbol link is not for create a shortcut for a executable file.

You can check out the .desktop file spec at [here](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) or you can also open up your dde-launcher and right click at any of items and choose "send to desktop", then you'll get a `.desktop` file located at `~/Desktop/` , edit it with your fivorate text editor is okay.

If this is a feature request, feel free to reopen this issue with the missing sections provided which mentioned in the issue template.
