### ISSUE TITLE
High cpu load on dde-desktop using arch

### ISSUE THREAD

**Issue by phkorn** [linuxdeepin/dde-file-manager#370]
## Describe the bug
I have a constant cpu load with dde-desktop of 25% 
## To Reproduce
This is the hardware I use:

![image](https://user-images.githubusercontent.com/1607865/89182815-9a5fc600-d596-11ea-8285-432b11468db5.png)

I have just updated my deepin packages.

The version can be found here: https://www.archlinux.org/groups/x86_64/deepin/

![image](https://user-images.githubusercontent.com/1607865/89183242-37bafa00-d597-11ea-9c65-c8286bbf985b.png)

## Expected behavior
Much lower cpu usage

### Distro & Version
Arch 5.7.11-arch1-1

### Additional context
Since the package mantainer switch to the new deepin 20, my cpu usage spiked.

**Comment by deepin-CD** [comment]
@k0rn1 Please give us more detail about the issue.
And we need konw how to reproduce it.

**Comment by phkorn** [comment]
I have moved on from Deepin since then and I cannot reproduce it anymore.
