### ISSUE TITLE
Remembering maximisation

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-file-manager#38]
HOW TO REPRODUCE:
1. Maximise the file manager.
2. Close it.
3. Reopen it.

RESULT:
- Not maximised.

RELEVANT DETAILS:
- Did not happen in the previous version of Deepin.

SYSTEM SPECS:
- deepin-file-manager 1:4.6.2
- deepin-qt5integration 0.3.2
- deepin-mutter 3.20.32
- deepin-wm 1.9.30

**Comment by BLumia** [comment]
We've removed the remember maximum behavior after 15.7, your request have been recorded and we'll consider about if we should add it back.

Thank you for your feedback :)

**Comment by es20490446e** [comment]
@BLumia What was the rationale?

**Comment by es20490446e** [comment]
You know, for most work-flows, having a single maximised window per application and switching between them using the dock is the most confortable thing, as it maximises the screen real estate.

So if window maximisation is remembered in this context it eliminates the need to maximise the window each time you launch the application.

**Comment by BLumia** [comment]
@es20490446e I know that, this feature may be add back later but maybe not, no promise about this. 

Personally for the daily development work I hardly did maximum the file manager window. imo the file manager app should let you navigate to the file you want to use, and then launch the associated application to process the file, then the file manager just got closed.

We'll consider about that, just keep an eye on it :)

**Comment by es20490446e** [comment]
Okay, have a nice day ;)

**Comment by es20490446e** [comment]
That said the rationale why MacOS doesn't use maximise is broken. You don't maximise only for being able to see all the information you can of that window, but also to hide all the information that it's not useful at that particular time. It's a tool for focus.

**Comment by es20490446e** [comment]
This is a recurrent say I have: A good interface shows what's needed right now, or constantly. And hides everything else.

**Comment by BLumia** [comment]
> That said the rationale why MacOS doesn't use maximise is broken.

The reason we removed the remember maximum feature is we refactored the whole config file logic and we only implemented the feature which is listed in the PRD document. Simply as that.

We may add this feature back in future update (we'll reopen this issue when we start to do this), but not now since current schedule is full :(

You're welcome to submit a patch (to [our code review site](https://cr.deepin.io/)) if you can help us add this feature :)

**Comment by es20490446e** [comment]
I would love to but I'm already writing two libre applications, and refactoring one. Not to mention I'm making [screen color calibration](https://github.com/agalakhov/xiccd/issues/20) available for your desktop environment :P

**Comment by es20490446e** [comment]
The lack of maximisation also breaks the possibility of using the hot upper right corner function for closing the window.

**Comment by wangjia12** [comment]
https://github.com/linuxdeepin/internal-discussion/issues/423
The same issue.We will fix it soon.
