### ISSUE TITLE
列表显示的时候，文件夹不显示文件名

### ISSUE THREAD

**Issue by lizhuangs** [linuxdeepin/dde-file-manager#387]
列表显示的时候，最前面的文件夹，只有图标，没有名字。
也不知道是怎么出现这种问题，重置设置也不行。
怎么解决？
![71547941-968B-4dad-ABF0-A3FC3F20812E](https://user-images.githubusercontent.com/7904121/121283412-a1213d00-c90d-11eb-9ff7-4abc20fdbb93.png)

**Comment by deepin-CD** [comment]
可以在`名称`那一栏向右拖动，展开文件名称

**Comment by lizhuangs** [comment]
> 可以在`名称`那一栏向右拖动，展开文件名称

我知道，问题是我每次打开都默认是这样，总不可能每次都拖动吧？

**Comment by lizhuangs** [comment]
卸载重装也不行，文件管理器是有什么设置保存在哪里么？删除/usr/share/dde-file-manager也不行。

**Comment by liwl1991** [comment]
> 卸载重装也不行，文件管理器是有什么设置保存在哪里么？删除/usr/share/dde-file-manager也不行。

这个好处理呀，看我的帖子:https://bbs.deepin.org/zh/post/205982

**Comment by lizhuangs** [comment]
> > 卸载重装也不行，文件管理器是有什么设置保存在哪里么？删除/usr/share/dde-file-manager也不行。
> 
> 这个好处理呀，看我的帖子:https://bbs.deepin.org/zh/post/205982
最新的版本没有你说的那个配置文件。不过最新的~/.config/deepin/dde-file-manager.json有个GenericAttribute属性，我全删除就好使了。不确定是不是这个导致的。
