### ISSUE TITLE
Open in new tab when click with shift + left click in left panel

### ISSUE THREAD

**Issue by otavioschwanck** [linuxdeepin/dde-file-manager#40]
All other file manager have this feature, i really miss in deepin file manage

**Comment by BLumia** [comment]
Sorry but:

 - Which 'other' file manager did you means? I've tested nether dolphin nor nautilus has this feature.
 - Please use the issue template.

**Comment by wangjia12** [comment]
Sorry，this feature is not in our plan at the moment.
