### ISSUE TITLE
Japanese file names became square character

### ISSUE THREAD

**Issue by justaordinaryman** [linuxdeepin/dde-file-manager#404]
I got  files with japanese name but in file manager it's became square character how to fix it ?

![image](https://user-images.githubusercontent.com/85546841/126305912-c5550f9b-e715-4dbc-973b-1ec432a1a939.png)

**Comment by deepin-CD** [comment]
Please check if Japanese font is installed.

**Comment by justaordinaryman** [comment]
my bad yeah i missing CJK fonts on my system
