### ISSUE TITLE
Properties menu doesn't show the partition type

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#41]
Properties menu doesn't show the partition type.

I would like that the file manager would tell us what is the type of the partition. Example- NTFS, EXT4, EXT3, EXT2 etc.

**Comment by wangjia12** [comment]
在“磁盘信息”里显示文件系统类型。显示在设备类型下面一行。
文案：
【文件系统】
@zhuxiujuancindy 
@zccrs

**Comment by zhuxiujuancindy** [comment]
文案：
【文件系统】
【Filesystem】

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/40037/

**Comment by liuwen123** [comment]
+1

**Comment by liuwen123** [comment]
已修复
