### ISSUE TITLE
File Manager select file Window does not change Theme

### ISSUE THREAD

**Issue by Faran52** [linuxdeepin/dde-file-manager#46]
Whenever I try to upload the a file the select window does not have dark theme even though the file manager is applied to dark theme from the settings.

![image](https://user-images.githubusercontent.com/34020197/45938918-d5cafa00-bfe7-11e8-9b4b-d055f322e272.png)

**Comment by BLumia** [comment]
That's a known issue and it's designed to be like this at least for now... This behavior may change when the file manager app got support to following system theme.

I'm also not sure to tag this issue as a bug or a feature request, but this behavior will got change in future updates, so please keep an eye on it ;)
