### ISSUE TITLE
Preview / thumbnails in Deepin File Manager for image files larger than 30 MB

### ISSUE THREAD

**Issue by chris977** [linuxdeepin/dde-file-manager#47]
I would like to get preview thumbnails for image files (jpeg, png, etc.) for files larger than 30 MB. Nowadays DSLRs and other cameras generate image files much larger than that. The limit is now at 30 MB, as you can see here:
https://github.com/linuxdeepin/dde-file-manager/blob/master/dde-file-manager-lib/interfaces/dthumbnailprovider.cpp

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
