### ISSUE TITLE
Use defaultt file manager for file dialogs

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/dde-file-manager#49]
So, I am using nautilus, when I open a folder it works fine:

<img src="https://i.imgur.com/hd6QQWs.png">

But whenever I use the 'save as' it uses the dde-file-manager rather than the default manager:

<img src="https://i.imgur.com/oVA4WGp.png">

Which is this proccess:

<img src="https://i.imgur.com/4rqoYS2.png">

So, when using default applications, can we make it more consistent of the features the DDE uses?

**Comment by BLumia** [comment]
From Deepin File Manager setting.

Setting > Dialog > Use the file chooser dialog of Deepin File Manager

Turn this option off.

**Comment by ghost** [comment]
> From Deepin File Manager seeting.
> 
> Setting > Dialog > Use the file chooser dialog of Deepin File Manager
> 
> Turn this option off.

Perfect! Fully working now, thank you for making an awesome OS!
