### ISSUE TITLE
Cannot copy any file to Samsung phone

### ISSUE THREAD

**Issue by nalawneh** [linuxdeepin/dde-file-manager#50]
## Describe the bug

Cannot copy any file from my computer to *Samsung phone(i9500)* and show me the following error (_Failed to open the file, cause: Operation unsupported_) but I can copy the file from the phone to my computer. 

## To Reproduce

*To Reproduce this issue try to copy any type of file to Samsung mobile phone*

## Expected behavior

*Should be copy the file to my phone without any error like this*

## Screenshots
Please see the following screenshot:
![deepinscreenshot_select-area_20180928112534](https://user-images.githubusercontent.com/43668201/46197219-d3cba880-c311-11e8-8d9d-d04be33b9333.png)

## Enviroments

 - Distro: [Linux Deepin 15.7]
 - Version: [4.6.8.4-1]

**Comment by zccrs** [comment]
Do you have any other phones, can it copy files?

**Comment by SiamSami** [comment]
I think I have a somewhat similar problem to this.
I have a Samsung Android phone (J500H). I can copy anything but whenever I try to do so, Deepin file manager freezes.

I am using Deepin OS 15.7 and 1.8.2 version of Deepin file manager.

**Comment by SiamSami** [comment]
Does it work with other file managers such as nautilus?

**Comment by BLumia** [comment]
> I think I have a somewhat similar problem to this.
> I have a Samsung Android phone (J500H). I can copy anything but whenever I try to do so, Deepin file manager freezes.
> 
> I am using Deepin OS 15.7 and 1.8.2 version of Deepin file manager.

Did this still happens in current newest release (dde-file-manager 4.7.6 or 4.7.7)?

**Comment by SiamSami** [comment]
> Did this still happens in current newest release (dde-file-manager 4.7.6 or 4.7.7)?

No, it doesn't happen anymore.

**Comment by BLumia** [comment]
Then closing, feel free to create new issue at [developer center](https://github.com/linuxdeepin/developer-center/issues) if anyone still got similar issue :)

**Comment by ali1957** [comment]
the problem is still happening in deepin20, dde file manager 5.2
but problem is solved while installing another file manager(Nautilus)

**Comment by ghost** [comment]
O problema ainda acontece na utima versão do deepin 1003. O problema só foi resolvido instalando outro gerenciador de arquivos.

![Screen Capture_select-area_20201029151012](https://user-images.githubusercontent.com/46272374/97614767-1e401780-19f9-11eb-9b13-c75a548b82b6.png)

**Comment by deejungx** [comment]
I had the same issue too. Also solved it using another file manager - lxqt file manager.
