### ISSUE TITLE
Doesn't change battery icon when charger is plugged or unplugged

### ISSUE THREAD

**Issue by Silvered99** [linuxdeepin/dde-file-manager#52]
## Bug description

The battery icon doesn't change when charger is plugged or unplugged in laptop. It stays the same since the boot i.e. it shows charging if the charger was connected at the time of boot else doesn't.

## Enviroments

 - Distro: [Arch Linux - Deepin Desktop Enviroment]
 - Version: [15.7]

**Comment by BLumia** [comment]
Thank you for reporting the bug. But you are probably reported to the wrong repo. The issue you've reported is probably an issue of a built-in plugin of dde-dock, not dde-file-manager.

You can simply report to [Developer Center](https://github.com/linuxdeepin/developer-center/issues) repo if you don't know the issue belongs to which repo and we'll help you address the bug then :)
