### ISSUE TITLE
"Paste" option on the right click menu of a folder

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#54]
## Is your feature request related to a problem? Please describe.

When I copy/cut a file/folder, I want to paste into a folder without opening it. I want to paste into that folder by right-clicking on it and selecting "Paste".

## Describe the solution you'd like

I want the "Paste" option on the right click menu of a folder.

**Comment by BLumia** [comment]
After discussion with product manager, we are going to implement this feature. Gotta close this issue for now :)
