### ISSUE TITLE
Failed to compile dde-dock,pluginsiteminterface.h: No such file or directory

### ISSUE THREAD

**Issue by windowsair** [linuxdeepin/dde-file-manager#58]
./dde-file-manager/dde-dock-plugins/disk-mount/diskmountplugin.h:31:10: fatal error: pluginsiteminterface.h: No such file or directory

**Comment by reionwong** [comment]
youou need to install dde-dock-dev.

**Comment by windowsair** [comment]
> youou need to install dde-dock-dev.


I want to compile dde-dock, but it doesn't seem to give a specific process of compilation.

**Comment by BLumia** [comment]
Do `apt build-dep dde-dock` and try again. Simply load the project into your QtCreator and build it will works.

btw, `dde-dock` is not a part of `dde-file-manager`, I recommend you create issue at [Developer Center](https://github.com/linuxdeepin/developer-center/issues/) if you are not sure your issue related to which repo.

**Comment by windowsair** [comment]
> Do `apt build-dep dde-dock` and try again. Simply load the project into your QtCreator and build it will works.
> 
> btw, `dde-dock` is not a part of `dde-file-manager`, I recommend you create issue at [Developer Center](https://github.com/linuxdeepin/developer-center/issues/) if you are not sure your issue related to which repo.


thx! I compiled the dde-file-manager, but it relies on the dde-dock

**Comment by BLumia** [comment]
> thx! I compiled the dde-file-manager, but it relies on the dde-dock

Whoops, do `apt build-dep dde-file-manager` will works, take a look at the build script in `debian/` will also helps if you are familiar with debian packaging :-)

**Comment by windowsair** [comment]
> > thx! I compiled the dde-file-manager, but it relies on the dde-dock
> 
> Whoops, do `apt build-dep dde-file-manager` will works, take a look at the build script in `debian/` will also helps if you are familiar with debian packaging :-)


I tried to copy the header files in dde-dock to the corresponding directory, then it worked  :-)
