### ISSUE TITLE
auto mount of windows partitons 

### ISSUE THREAD

**Issue by tecivan** [linuxdeepin/dde-file-manager#59]
every time i boot or login from logout, I'm requested to input password to mount the other partition. What i hate is that this happens when I don't really need it. How can i disable this.
I have no auto mount rules on fstab and am not planing to have any. 
here is the window am talking about

![deepinscreenshot_20170825185137](https://user-images.githubusercontent.com/15979652/29721742-0310374e-89c7-11e7-9550-f14bdedb5828.png)

> am using arch linux

**Comment by lsblk** [comment]
![deepin-screen-recorder_select area_20170826175316](https://user-images.githubusercontent.com/11588373/29740392-083d6f9a-8a88-11e7-8875-ccb4f77d70d8.gif)
using arch linux too

**Comment by tecivan** [comment]
thank you 👍
