### ISSUE TITLE
Can't open multiple files at once

### ISSUE THREAD

**Issue by LeCharlatan** [linuxdeepin/dde-file-manager#6]
Hi,

The file manager can't "open with..." if more than one file is selected.
For instance, if I select 3 pictures and click right mouse button to open with GIMP, the popup doesn't include "open with..." option, it only shows "open with..." when select only one file.

This is very annoying cause can't open multiple files at once, except with default's app.

Deepin Desktop Environment could be better with some features like this one :)

Thanks

**Comment by SHIHUAMarryMe** [comment]
Do not support this in the design of filemanager.

**Comment by wangjia12** [comment]
多选打开逻辑
如果右键多选文件为同一类型文件，支持“打开”和“打开方式”，直接一次打开到应用；
如果是不同文件，不支持打开和打开方式。
@zccrs

**Comment by wangjia12** [comment]
是15.8.2里面的内容，这个issue选不到里程碑

**Comment by zccrs** [comment]
@wangjia12 是因为这个issue在dde-file-manager项目中

**Comment by BLumia** [comment]
This should now supported in tag 4.7.1.9 release (https://github.com/linuxdeepin/dde-file-manager/commit/250cc486bec256fa9c8831c1cb63c22b237d4f71). Please wait for the package maintainer of the distro which you are using to delivery the new version of dde-file-manager :)

**Comment by LeCharlatan** [comment]
Nice, this feature will be very useful
Thanks !
