### ISSUE TITLE
增强列表模式下重命名时的色彩对比

### ISSUE THREAD

**Issue by dongfengweixiao** [linuxdeepin/dde-file-manager#60]
![_virtualbox machine_20181030223519](https://user-images.githubusercontent.com/1300822/47726054-b1240b00-dc94-11e8-8ea9-436373c72459.png)
![_virtualbox machine_20181030223509](https://user-images.githubusercontent.com/1300822/47726056-b1bca180-dc94-11e8-9a94-6da9c6e2ca45.png)
![_dde-file-manager_20181030223819](https://user-images.githubusercontent.com/1300822/47726074-b7b28280-dc94-11e8-82b3-25aafbee4555.png)
![_dde-file-manager_20181030223746](https://user-images.githubusercontent.com/1300822/47726075-b7b28280-dc94-11e8-8d40-223c8aa1dc54.png)

对比 Windows 下的列表模式文件被选中和文件处于改名状态的样式，可以发现，不管在文件名的长度如何，都可以明确的显示其处于选中状态还是改名状态。
但是对比 DDE 的文件管理器，在选中时使用的是浅蓝色，当变为rename状态时，底色变为深蓝色，但是文字的背景依旧是浅蓝色，且和背景的深蓝色之间仅有很小的间隔。当文件名的长度不是很长时，并没有太多的影响，但是当文件名的长度很长（超过可显示的长度）就会导致用户无法直观的理解当前状态。
![_dde-file-manager_20181030224539](https://user-images.githubusercontent.com/1300822/47726538-a453e700-dc95-11e8-8425-05543a56b8a2.png)

**Comment by wangjia12** [comment]
@zccrs 刚找 @shule1987 看了，说这个是bug。找他确认效果吧。

**Comment by shule1987** [comment]
@zccrs 把列表模式重命名的文字选中的背景颜色改成rgba(255,255,255,0.4)

**Comment by dongfengweixiao** [comment]
理论上，在宫格模式下，如果文件名的长度恰好充满N行，则也比较难以区别（当然了，在宫格模式下，整个文件名都在视野范围内，所以不更改也没用关系）。

**Comment by BLumia** [comment]
https://cr.deepin.io/#/c/dde/dde-file-manager/+/39876/

**Comment by zccrs** [comment]
@shule1987 看一下现在的效果对不对

**Comment by shule1987** [comment]
昨天装了上面的cr。没看到效果

**Comment by BLumia** [comment]
> @shule1987 : 昨天装了上面的 cr。没看到效果

因为你给的颜色就是这样的.......

**Comment by shule1987** [comment]
已经验证

**Comment by liuwen123** [comment]
已修复
