### ISSUE TITLE
anything搜索范围问题

### ISSUE THREAD

**Issue by hadeskaiser** [linuxdeepin/dde-file-manager#61]
在/分区搜索的时候不会搜索其他的分区比如/home比如/opt.如何像everthing一样在所有结果里面查询需要的文件？

**Comment by BLumia** [comment]
您好，是会搜索的。如果不会索引的话应该是 bug （我这边没能复现），可以提供一些你觉得有用的信息帮助我们定位 bug。

另外正如你在创建该 issue 时看到的 issue template，我们已经计划逐步把所有 issue 统一到 developer-center 项目中处理（处理完当前 repo 的所有 Open 状态的 issue 之后我们会把当前 repo 的 issue 页面入口关掉），所以如果您确认是 bug 的话，请在 [developer-center](https://github.com/linuxdeepin/developer-center/issues/) 里提交 issue ，多谢配合。
