### ISSUE TITLE
18.10 Support?

### ISSUE THREAD

**Issue by avarayr** [linuxdeepin/dde-file-manager#62]
I can't install dde-file-manager on Ubuntu 18.10 Cosmic. Is it not supported?

**Comment by BLumia** [comment]
That‘s a packaging issue, which you should contact package maintainer for support (afaik, for the file manager, there is no official support for debian/ubuntu for now, but you can track the state at [here](https://tracker.debian.org/teams/pkg-deepin/)). If you want to build it and install it manually, you may need get all depts installed, which also included other packages are not included in ubuntu for now and you should also compile it and install it by yourself.

btw, this issue board is no longer accepting new issue, for further discussion, please open up your issue to [Developer Center](https://github.com/linuxdeepin/developer-center/issues), thx :)
