### ISSUE TITLE
Can't build on Manjaro

### ISSUE THREAD

**Issue by alexandre1985** [linuxdeepin/dde-file-manager#63]
I have cloned this repoand I'm trying to build the app.
I have done:
```
mkdir Build/
cd Build
qmake ..
```
Now when I do `make` I get a compile error. The error is this:

> /home/daniel/dev/opensource/dde-file-manager/dialogs/dtaskdialog.cpp:82:75: error: no matching function for call to ‘Dtk::Widget::DDialog::setIcon(QIcon, QSize)’
             dialog.setIcon(QIcon::fromTheme("dialog-error"), QSize(64, 64));
                                                                           ^
In file included from /home/daniel/dev/opensource/dde-file-manager/dialogs/dtaskdialog.h:39,
                 from /home/daniel/dev/opensource/dde-file-manager/dialogs/dtaskdialog.cpp:25:
/usr/include/libdtk-2.0.6/DWidget/ddialog.h:107:10: note: candidate: ‘void Dtk::Widget::DDialog::setIcon(const QIcon&)’
     void setIcon(const QIcon &icon);
          ^~~~~~~
/usr/include/libdtk-2.0.6/DWidget/ddialog.h:107:10: note:   candidate expects 1 argument, 2 provided
make[1]: *** [Makefile:3701: dtaskdialog.o] Error 1
make[1]: Leaving directory '/home/daniel/dev/opensource/dde-file-manager/Build/dde-file-manager-lib'
make: *** [Makefile:103: sub-dde-file-manager-lib-make_first] Error 2

I can't find a dialog-error theme to install on my OS.

**Comment by BLumia** [comment]
You should use the same tag version of dde-file-manager as Manjaro use. The master branch contains the most recent release bit it also need most recent version of it's depts installed (for your case, **dtkwidget** is outdated). You can also check out the PKGBUILD script which the package maintainer of your distro use to know about how they build the package.

We no longer accepting new issue from dde-file-manager repo, please move to developer-center for further discussion :)
