### ISSUE TITLE
Can dde-file-manager support this? ( look at the picture)

### ISSUE THREAD

**Issue by FurryWolfX** [linuxdeepin/dde-file-manager#65]
Can dde-file-manager support this?

It's a good feature of macOS, and elementryOS has the feature too.

(this picture is the default file manager of elementryOS )

![](https://i.loli.net/2019/01/11/5c38b89ebdcd6.png)

**Comment by BLumia** [comment]
AFAIK currently no plan about this kinds of view, but not sure about if it will be made in the future.

We no longer accepting new issue from dde-file-manager (this) repo, please move to [developer-center](https://github.com/linuxdeepin/developer-center/issues) for further discussion :)
