### ISSUE TITLE
Disable auto open usb drive with dd-file-manager

### ISSUE THREAD

**Issue by igorvisi** [linuxdeepin/dde-file-manager#7]
How to disable auto open usb drive with dd-file-manager ?

**Comment by dragondjf** [comment]
sudo apt-get install dconf-editor
open dconf-editor and set follwing steps:
org.gnome.desktop.media-handing　automount　false 
org.gnome.desktop.media-handing　automount-open false

**Comment by dragondjf** [comment]
This has been fixed by Release 1.4; You can experience in tomorrow。
