### ISSUE TITLE
Can't change file permissions

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#8]
We can't change permissions of folders and files.

Please add a feature to change file and folder permissions.

**Comment by SHIHUAMarryMe** [comment]
You can change it through "Property".

**Comment by BLumia** [comment]
Thank you for your feedback.

This feature was in older version of file manager and it's removed for some reason, and this feature will be add back in future release. Please look forward to it :smile:

**Comment by SalahAdDin** [comment]
I have still the same problem, but i'm not sure if it is a conflict between `nautilus` and `deepin-file-manager`.

**Comment by BLumia** [comment]
This feature is just not included in the current release of `dde-file-manager`, we removed this feature for some reason some times ago, and it will be added back in the next major version. So just keep an eye on it and enjoy 😝

**Comment by BLumia** [comment]
Hi and since [#eee3155](https://github.com/linuxdeepin/dde-file-manager/commit/eee31551356875d23bec82c5cdfac1de774d9c7b) we can set file permission in right click context menu, this feature will be included in v1.8 release so please wait and enjoy :)
