### ISSUE TITLE
Error while compiling....

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-file-manager#9]
When try to compile dde-file-manager, it says, "DAction: No such file or directory".

**Comment by SHIHUAMarryMe** [comment]
Do you compile filemanager in master banch?
If yes, please checkout to develop2.0, then compile.
The master branch was deprecated!

**Comment by SiamSami** [comment]
Well, develop2.0 has an issue with my OS. Qt creator says, unexpected UTF-8 bom. The problem is with the .pro file.

**Comment by SHIHUAMarryMe** [comment]
You can save it with utf-8 bom. 
How to save it with utf-8 bom?  The option is in right-mouse menu.

**Comment by BLumia** [comment]
Direct clone it to your local disk and compile it shouldn't have that problem, could you please provide some more details about that? Which distro are you using? Did you modify any source file before compiling? Provide the compiler's output also helps.

Thanks.

**Comment by SiamSami** [comment]
Thanks BLumia!
I don't have the problem with utf-8 bom anymore.
My NEW PROBLEM is that, qtcreator is outputting the following, "deepin-anything/fs_buf.h: No such file or directory"
Could you tell me what to do?
I am using Ubuntu 18.04 with latest updates. Any help would be greatly appreciated.

**Comment by BLumia** [comment]
Newer version of dde-file-manager requires [deepin-anything](https://github.com/linuxdeepin/deepin-anything) to build&run, so you should check it out first.

**Comment by SiamSami** [comment]
How do I do that?

**Comment by SHIHUAMarryMe** [comment]
@SiamSami 
You need install **deepin-anything-dkms, deepin-anything-dev, deepin-anything-libs**.  But you are in ubuntu now. You'd better to complie deepin-anything in your computer.
It is simple. deepin-anything depend on **linux-headers-generic**.Y
You can clone it, then cd to the dir which the deepin-anything is in.
Then make install. OK!

**Comment by BLumia** [comment]
Friendly reminder, the master branch is no longer a deprecated branch, it's the last stable version of dde-file-manager now.

**Comment by SiamSami** [comment]
Maybe I should tell you guys that I'm no longer using Ubuntu... I am now using Arch Linux... The version of Qt is 5.10.1-8

Also, I am getting this error while trying to compiling it, 
"[Makefile:95: sub-dde-file-manager-lib-qmake_all] Error 3"

Thanks for all the help, by the way!!!

**Comment by BLumia** [comment]
Not sure if got a successful build now...

For Arch Linux user, you can always checkout the [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/deepin-file-manager) file provided by package maintainer :)

We also updated README file of this project to help people about how to build this project. btw, we switched the development branch to **master** now.

Feel free to reopen this issue if you got any further questions about building the file manager :)
